import { ToolConfig } from './types'

export const toolConfigs: Record<string, ToolConfig> = {
  'legal-email-drafter': {
    id: 'legal-email-drafter',
    name: 'Legal Email Drafter',
    slug: 'legal-email-drafter',
    category: 'Document Drafting',
    description: 'Draft professional legal emails with appropriate tone and precision',
    longDescription: 'Generate professional legal communications for clients, opposing counsel, or colleagues. Choose from various tones and automatically format your email with proper legal language.',
    inputFields: [
      {
        name: 'recipient',
        label: 'Recipient',
        type: 'text',
        placeholder: 'e.g., Client, Opposing Counsel, Judge',
        required: true,
        maxLength: 200,
      },
      {
        name: 'subject',
        label: 'Subject',
        type: 'text',
        placeholder: 'e.g., Case Status Update, Discovery Response',
        required: true,
        maxLength: 200,
      },
      {
        name: 'context',
        label: 'Context & Key Points',
        type: 'textarea',
        placeholder: 'Describe what you want to communicate...',
        required: true,
        maxLength: 2000,
        helpText: 'Include important details, dates, and any specific points to address',
      },
      {
        name: 'tone',
        label: 'Tone',
        type: 'select',
        required: true,
        options: ['Professional', 'Formal', 'Friendly', 'Firm', 'Persuasive'],
      },
    ],
    outputFormat: 'text',
    complexity: 'simple',
    estimatedTime: '5-10 seconds',
    requiredTier: 'free',
    aiModel: {
      free: 'Gemini 1.5 Flash',
      starter: 'Claude Haiku',
      pro: 'Claude Haiku',
      advanced: 'Claude Haiku',
    },
    samplePrompts: [
      'Draft an email to a client updating them on case progress',
      'Write to opposing counsel requesting extension for discovery',
      'Send a formal notice to a third party regarding document production',
    ],
    relatedTools: ['client-status-update', 'demand-letter-generator'],
    useCases: [
      'Client communication',
      'Opposing counsel correspondence',
      'Court communications',
      'Internal team updates',
    ],
    icon: '✉️',
  },
  
  'case-law-summarizer': {
    id: 'case-law-summarizer',
    name: 'Case Law Summarizer',
    slug: 'case-law-summarizer',
    category: 'Legal Research',
    description: 'Instant summaries of judicial opinions with key holdings',
    longDescription: 'Get concise 2-3 paragraph summaries of complex court decisions, including facts, issues, holdings, and reasoning. Perfect for quick case analysis.',
    inputFields: [
      {
        name: 'caseText',
        label: 'Case Text or Citation',
        type: 'textarea',
        placeholder: 'Paste case text or provide citation...',
        required: true,
        maxLength: 20000,
        helpText: 'You can paste the full case text or provide a citation',
      },
      {
        name: 'focusArea',
        label: 'Focus Area (Optional)',
        type: 'text',
        placeholder: 'e.g., damages, jurisdiction, specific issue',
        required: false,
        maxLength: 200,
      },
    ],
    outputFormat: 'markdown',
    complexity: 'medium',
    estimatedTime: '10-20 seconds',
    requiredTier: 'starter',
    aiModel: {
      free: 'Not available',
      starter: 'Claude Haiku',
      pro: 'Claude Sonnet',
      advanced: 'Claude Sonnet',
    },
    samplePrompts: [
      'Summarize Smith v. Jones, 123 F.3d 456 (9th Cir. 2020)',
      'Extract key holdings from this appellate decision',
      'Focus on damages discussion in this case',
    ],
    relatedTools: ['legal-research-assistant', 'legal-issue-spotter'],
    useCases: [
      'Case research',
      'Brief writing',
      'Client advisories',
      'Case law database',
    ],
    icon: '📋',
  },

  'contract-risk-analyzer': {
    id: 'contract-risk-analyzer',
    name: 'Contract Risk Analyzer',
    slug: 'contract-risk-analyzer',
    category: 'Contract Review',
    description: 'AI-powered contract analysis with risk scoring and recommendations',
    longDescription: 'Upload or paste a contract to receive comprehensive risk analysis, including unfavorable terms, missing clauses, and recommended changes. Get a risk score and actionable insights.',
    inputFields: [
      {
        name: 'contractText',
        label: 'Contract Text',
        type: 'textarea',
        placeholder: 'Paste your contract here...',
        required: true,
        maxLength: 50000,
        helpText: 'Full contract text - we support agreements up to 50,000 characters',
      },
      {
        name: 'contractType',
        label: 'Contract Type',
        type: 'select',
        required: true,
        options: [
          'Vendor Agreement',
          'Employment Contract',
          'NDA',
          'Lease Agreement',
          'Service Agreement',
          'Other',
        ],
      },
      {
        name: 'perspective',
        label: 'Review From Perspective Of',
        type: 'select',
        required: true,
        options: ['Buyer', 'Seller', 'Landlord', 'Tenant', 'Employer', 'Employee', 'Neutral'],
      },
    ],
    outputFormat: 'structured',
    complexity: 'high',
    estimatedTime: '20-40 seconds',
    requiredTier: 'pro',
    aiModel: {
      free: 'Not available',
      starter: 'Not available',
      pro: 'Claude Sonnet',
      advanced: 'Claude Opus',
    },
    samplePrompts: [
      'Analyze this vendor agreement for unfavorable terms',
      'Review employment contract from employer perspective',
      'Check lease agreement for missing standard clauses',
    ],
    relatedTools: ['contract-clause-extractor', 'contract-summary-generator'],
    useCases: [
      'Due diligence',
      'Contract negotiation',
      'Risk mitigation',
      'Vendor management',
    ],
    icon: '⚖️',
  },

  'deposition-summarizer': {
    id: 'deposition-summarizer',
    name: 'Deposition Summarizer',
    slug: 'deposition-summarizer',
    category: 'Litigation Support',
    description: 'Create topical or page-line deposition summaries',
    longDescription: 'Transform lengthy deposition transcripts into concise, organized summaries. Choose between topical organization or traditional page-line format. Perfect for trial prep.',
    inputFields: [
      {
        name: 'transcript',
        label: 'Deposition Transcript',
        type: 'textarea',
        placeholder: 'Paste deposition transcript...',
        required: true,
        maxLength: 100000,
        helpText: 'We can process transcripts up to 300 pages',
      },
      {
        name: 'format',
        label: 'Summary Format',
        type: 'select',
        required: true,
        options: ['Topical', 'Page-Line', 'Executive Summary'],
      },
      {
        name: 'focusTopics',
        label: 'Focus Topics (Optional)',
        type: 'multiselect',
        required: false,
        options: [
          'Timeline of Events',
          'Damages',
          'Liability',
          'Credibility',
          'Expert Opinions',
          'Document References',
        ],
      },
    ],
    outputFormat: 'markdown',
    complexity: 'high',
    estimatedTime: '30-60 seconds',
    requiredTier: 'pro',
    aiModel: {
      free: 'Not available',
      starter: 'Not available',
      pro: 'Claude Sonnet',
      advanced: 'Claude Opus',
    },
    samplePrompts: [
      'Create topical summary focused on timeline and damages',
      'Generate page-line summary for impeachment prep',
      'Executive summary highlighting key admissions',
    ],
    relatedTools: ['discovery-request-generator', 'motion-to-dismiss-drafter'],
    useCases: [
      'Trial preparation',
      'Case assessment',
      'Impeachment strategy',
      'Settlement negotiation',
    ],
    icon: '🎯',
  },

  'legal-memo-writer': {
    id: 'legal-memo-writer',
    name: 'Legal Memo Writer',
    slug: 'legal-memo-writer',
    category: 'Document Drafting',
    description: 'Research memos with IRAC structure',
    longDescription: 'Generate comprehensive legal memoranda using the IRAC (Issue, Rule, Application, Conclusion) format. Perfect for internal analysis and client advisories.',
    inputFields: [
      {
        name: 'issue',
        label: 'Legal Issue',
        type: 'textarea',
        placeholder: 'State the legal issue...',
        required: true,
        maxLength: 1000,
      },
      {
        name: 'facts',
        label: 'Relevant Facts',
        type: 'textarea',
        placeholder: 'Provide the relevant facts...',
        required: true,
        maxLength: 5000,
      },
      {
        name: 'jurisdiction',
        label: 'Jurisdiction',
        type: 'text',
        placeholder: 'e.g., California, 9th Circuit, Federal',
        required: true,
        maxLength: 100,
      },
      {
        name: 'clientQuestion',
        label: 'Client Question',
        type: 'textarea',
        placeholder: 'What does the client want to know?',
        required: false,
        maxLength: 1000,
      },
    ],
    outputFormat: 'markdown',
    complexity: 'high',
    estimatedTime: '30-45 seconds',
    requiredTier: 'pro',
    aiModel: {
      free: 'Not available',
      starter: 'Not available',
      pro: 'Claude Sonnet',
      advanced: 'Claude Opus',
    },
    samplePrompts: [
      'Analyze liability for slip and fall in California',
      'Research employment discrimination claim viability',
      'Assess breach of contract damages',
    ],
    relatedTools: ['legal-research-assistant', 'case-law-summarizer'],
    useCases: [
      'Client advisories',
      'Internal research',
      'Case assessment',
      'Strategy planning',
    ],
    icon: '📝',
  },

  'legal-issue-spotter': {
    id: 'legal-issue-spotter',
    name: 'Legal Issue Spotter',
    slug: 'legal-issue-spotter',
    category: 'Legal Research',
    description: 'Analyze fact patterns to identify potential legal issues',
    longDescription: 'Upload client fact scenarios and receive comprehensive analysis of potential legal issues, relevant laws, and recommended actions. Perfect for case intake and initial assessment.',
    inputFields: [
      {
        name: 'factPattern',
        label: 'Fact Pattern',
        type: 'textarea',
        placeholder: 'Describe the client situation in detail...',
        required: true,
        maxLength: 10000,
        helpText: 'Include dates, parties involved, actions taken, and outcomes',
      },
      {
        name: 'jurisdiction',
        label: 'Jurisdiction',
        type: 'text',
        placeholder: 'e.g., California, New York, Federal',
        required: true,
        maxLength: 100,
      },
      {
        name: 'practiceArea',
        label: 'Practice Area (Optional)',
        type: 'select',
        required: false,
        options: ['Employment', 'Contract', 'Tort', 'Property', 'Corporate', 'Criminal', 'Family', 'All'],
      },
    ],
    outputFormat: 'markdown',
    complexity: 'high',
    estimatedTime: '20-40 seconds',
    requiredTier: 'pro',
    aiModel: {
      free: 'Not available',
      starter: 'Not available',
      pro: 'Claude Sonnet',
      advanced: 'Claude Opus',
    },
    samplePrompts: [
      'Identify issues in wrongful termination scenario',
      'Spot liability issues in construction dispute',
      'Analyze breach of NDA fact pattern',
    ],
    relatedTools: ['legal-research-assistant', 'legal-memo-writer'],
    useCases: [
      'Case intake',
      'Initial consultation',
      'Conflict checking',
      'Fee estimation',
    ],
    icon: '🔍',
  },

  'demand-letter-generator': {
    id: 'demand-letter-generator',
    name: 'Demand Letter Generator',
    slug: 'demand-letter-generator',
    category: 'Document Drafting',
    description: 'Persuasive demand letters with legal authority',
    longDescription: 'Create professional demand letters for pre-litigation disputes. Include damages, legal basis, and deadline for response. Perfect for collections, contract breaches, and property disputes.',
    inputFields: [
      {
        name: 'claimant',
        label: 'Your Client Name',
        type: 'text',
        placeholder: 'e.g., John Smith',
        required: true,
        maxLength: 200,
      },
      {
        name: 'respondent',
        label: 'Recipient Name',
        type: 'text',
        placeholder: 'e.g., ABC Corporation',
        required: true,
        maxLength: 200,
      },
      {
        name: 'claimBasis',
        label: 'Basis of Claim',
        type: 'textarea',
        placeholder: 'Describe the breach, incident, or basis for demand...',
        required: true,
        maxLength: 3000,
      },
      {
        name: 'damages',
        label: 'Damages Sought',
        type: 'text',
        placeholder: 'e.g., $50,000 for breach of contract',
        required: true,
        maxLength: 500,
      },
      {
        name: 'deadline',
        label: 'Response Deadline (Days)',
        type: 'select',
        required: true,
        options: ['10', '15', '20', '30'],
      },
      {
        name: 'tone',
        label: 'Tone',
        type: 'select',
        required: true,
        options: ['Professional', 'Firm', 'Aggressive'],
      },
    ],
    outputFormat: 'text',
    complexity: 'medium',
    estimatedTime: '15-25 seconds',
    requiredTier: 'starter',
    aiModel: {
      free: 'Not available',
      starter: 'Claude Haiku',
      pro: 'Claude Sonnet',
      advanced: 'Claude Sonnet',
    },
    samplePrompts: [
      'Demand payment for unpaid invoices',
      'Request return of security deposit',
      'Demand compensation for breach of contract',
    ],
    relatedTools: ['legal-email-drafter', 'contract-summary-generator'],
    useCases: [
      'Collections',
      'Contract disputes',
      'Property damage',
      'Pre-litigation negotiation',
    ],
    icon: '📨',
  },

  'contract-drafter-nda': {
    id: 'contract-drafter-nda',
    name: 'Contract Drafter (NDA)',
    slug: 'contract-drafter-nda',
    category: 'Document Drafting',
    description: 'Generate mutual or unilateral NDAs',
    longDescription: 'Create customized Non-Disclosure Agreements (NDAs) with standard protective clauses. Choose between mutual and unilateral agreements. Includes confidentiality obligations, term, and remedies.',
    inputFields: [
      {
        name: 'ndaType',
        label: 'NDA Type',
        type: 'select',
        required: true,
        options: ['Mutual', 'Unilateral (One-Way)'],
      },
      {
        name: 'party1',
        label: 'Disclosing Party',
        type: 'text',
        placeholder: 'Company or individual name',
        required: true,
        maxLength: 200,
      },
      {
        name: 'party2',
        label: 'Receiving Party',
        type: 'text',
        placeholder: 'Company or individual name',
        required: true,
        maxLength: 200,
      },
      {
        name: 'purpose',
        label: 'Purpose',
        type: 'textarea',
        placeholder: 'Describe the purpose of disclosure...',
        required: true,
        maxLength: 1000,
      },
      {
        name: 'term',
        label: 'Confidentiality Term',
        type: 'select',
        required: true,
        options: ['1 year', '2 years', '3 years', '5 years', 'Indefinite'],
      },
      {
        name: 'jurisdiction',
        label: 'Governing Law',
        type: 'text',
        placeholder: 'e.g., California, Delaware',
        required: true,
        maxLength: 100,
      },
    ],
    outputFormat: 'text',
    complexity: 'medium',
    estimatedTime: '20-30 seconds',
    requiredTier: 'pro',
    aiModel: {
      free: 'Not available',
      starter: 'Not available',
      pro: 'Claude Sonnet',
      advanced: 'Claude Opus',
    },
    samplePrompts: [
      'Mutual NDA for business partnership discussions',
      'Unilateral NDA for employee hiring',
      'NDA for vendor evaluation process',
    ],
    relatedTools: ['contract-risk-analyzer', 'employment-contract-generator'],
    useCases: [
      'Business negotiations',
      'Employee onboarding',
      'Vendor evaluation',
      'Partnership discussions',
    ],
    icon: '🔒',
  },

  'contract-clause-extractor': {
    id: 'contract-clause-extractor',
    name: 'Contract Clause Extractor',
    slug: 'contract-clause-extractor',
    category: 'Contract Review',
    description: 'Extract specific clauses across contracts',
    longDescription: 'Upload multiple contracts and extract specific clause types (e.g., termination, indemnification, payment terms). Perfect for due diligence and contract portfolio analysis.',
    inputFields: [
      {
        name: 'contractText',
        label: 'Contract Text',
        type: 'textarea',
        placeholder: 'Paste contract text here...',
        required: true,
        maxLength: 50000,
      },
      {
        name: 'clauseType',
        label: 'Clause Type to Extract',
        type: 'select',
        required: true,
        options: [
          'Termination',
          'Payment Terms',
          'Indemnification',
          'Liability Limitation',
          'Confidentiality',
          'Non-Compete',
          'Dispute Resolution',
          'Force Majeure',
          'All Standard Clauses',
        ],
      },
    ],
    outputFormat: 'structured',
    complexity: 'medium',
    estimatedTime: '15-25 seconds',
    requiredTier: 'starter',
    aiModel: {
      free: 'Not available',
      starter: 'Claude Haiku',
      pro: 'Claude Sonnet',
      advanced: 'Claude Opus',
    },
    samplePrompts: [
      'Extract all termination clauses from vendor contracts',
      'Find payment terms across service agreements',
      'Identify liability limitations in all contracts',
    ],
    relatedTools: ['contract-risk-analyzer', 'contract-summary-generator'],
    useCases: [
      'Due diligence',
      'Contract portfolio review',
      'Compliance checking',
      'Template creation',
    ],
    icon: '✂️',
  },

  'contract-summary-generator': {
    id: 'contract-summary-generator',
    name: 'Contract Summary Generator',
    slug: 'contract-summary-generator',
    category: 'Contract Review',
    description: 'Executive summaries of complex agreements',
    longDescription: 'Generate concise 1-page summaries of lengthy contracts highlighting key terms, obligations, dates, and risks. Perfect for executive briefings and quick reference.',
    inputFields: [
      {
        name: 'contractText',
        label: 'Contract Text',
        type: 'textarea',
        placeholder: 'Paste full contract here...',
        required: true,
        maxLength: 50000,
        helpText: 'We can summarize contracts up to 100 pages',
      },
      {
        name: 'focusAreas',
        label: 'Focus Areas (Optional)',
        type: 'multiselect',
        required: false,
        options: [
          'Key Financial Terms',
          'Important Dates',
          'Obligations',
          'Termination Rights',
          'Risk Factors',
        ],
      },
    ],
    outputFormat: 'markdown',
    complexity: 'medium',
    estimatedTime: '15-30 seconds',
    requiredTier: 'starter',
    aiModel: {
      free: 'Not available',
      starter: 'Claude Haiku',
      pro: 'Claude Sonnet',
      advanced: 'Claude Sonnet',
    },
    samplePrompts: [
      'Summarize 50-page vendor agreement',
      'Create executive summary of lease contract',
      'Brief overview of M&A purchase agreement',
    ],
    relatedTools: ['contract-risk-analyzer', 'contract-clause-extractor'],
    useCases: [
      'Executive briefings',
      'Client updates',
      'Quick reference',
      'Deal summaries',
    ],
    icon: '📄',
  },

  'discovery-request-generator': {
    id: 'discovery-request-generator',
    name: 'Discovery Request Generator',
    slug: 'discovery-request-generator',
    category: 'Litigation Support',
    description: 'Generate interrogatories, RFPs, RFAs',
    longDescription: 'Create comprehensive discovery requests including interrogatories, requests for production, and requests for admission. Customized to case type and jurisdiction rules.',
    inputFields: [
      {
        name: 'requestType',
        label: 'Request Type',
        type: 'select',
        required: true,
        options: [
          'Interrogatories',
          'Requests for Production',
          'Requests for Admission',
          'All Three',
        ],
      },
      {
        name: 'caseType',
        label: 'Case Type',
        type: 'select',
        required: true,
        options: [
          'Personal Injury',
          'Contract Dispute',
          'Employment',
          'Property',
          'Intellectual Property',
          'Other',
        ],
      },
      {
        name: 'facts',
        label: 'Case Facts',
        type: 'textarea',
        placeholder: 'Brief description of the case...',
        required: true,
        maxLength: 3000,
      },
      {
        name: 'jurisdiction',
        label: 'Jurisdiction',
        type: 'text',
        placeholder: 'e.g., California, Federal',
        required: true,
        maxLength: 100,
      },
      {
        name: 'specificIssues',
        label: 'Specific Issues to Address (Optional)',
        type: 'textarea',
        placeholder: 'Any particular topics or issues to focus on...',
        required: false,
        maxLength: 1000,
      },
    ],
    outputFormat: 'text',
    complexity: 'medium',
    estimatedTime: '20-35 seconds',
    requiredTier: 'starter',
    aiModel: {
      free: 'Not available',
      starter: 'Claude Haiku',
      pro: 'Claude Sonnet',
      advanced: 'Claude Sonnet',
    },
    samplePrompts: [
      'First set of interrogatories for car accident case',
      'RFPs for employment discrimination matter',
      'RFAs for breach of contract litigation',
    ],
    relatedTools: ['deposition-summarizer', 'motion-to-dismiss-drafter'],
    useCases: [
      'Initial discovery',
      'Follow-up requests',
      'Targeted discovery',
      'Standard requests',
    ],
    icon: '📝',
  },

  'motion-to-dismiss-drafter': {
    id: 'motion-to-dismiss-drafter',
    name: 'Motion to Dismiss Drafter',
    slug: 'motion-to-dismiss-drafter',
    category: 'Litigation Support',
    description: 'Draft motions with relevant case law',
    longDescription: 'Generate comprehensive motions to dismiss with legal arguments, case citations, and procedural requirements. Supports FRCP 12(b)(6) and state equivalents.',
    inputFields: [
      {
        name: 'complaintSummary',
        label: 'Complaint Summary',
        type: 'textarea',
        placeholder: 'Summarize the key allegations in the complaint...',
        required: true,
        maxLength: 5000,
      },
      {
        name: 'dismissalGrounds',
        label: 'Grounds for Dismissal',
        type: 'multiselect',
        required: true,
        options: [
          'Lack of Jurisdiction',
          'Failure to State a Claim',
          'Statute of Limitations',
          'Improper Venue',
          'Failure to Join Party',
          'Other',
        ],
      },
      {
        name: 'jurisdiction',
        label: 'Court/Jurisdiction',
        type: 'text',
        placeholder: 'e.g., Central District of California, California Superior Court',
        required: true,
        maxLength: 200,
      },
      {
        name: 'keyFacts',
        label: 'Key Supporting Facts',
        type: 'textarea',
        placeholder: 'Facts that support dismissal...',
        required: true,
        maxLength: 3000,
      },
    ],
    outputFormat: 'markdown',
    complexity: 'high',
    estimatedTime: '30-50 seconds',
    requiredTier: 'pro',
    aiModel: {
      free: 'Not available',
      starter: 'Not available',
      pro: 'Claude Sonnet',
      advanced: 'Claude Opus',
    },
    samplePrompts: [
      'Motion to dismiss for failure to state a claim',
      'Dismiss for lack of personal jurisdiction',
      'Motion based on statute of limitations',
    ],
    relatedTools: ['legal-research-assistant', 'case-law-summarizer'],
    useCases: [
      'Early case dismissal',
      'Jurisdictional challenges',
      'Procedural defenses',
      'Cost-effective defense',
    ],
    icon: '⚖️',
  },

  'manda-due-diligence-analyzer': {
    id: 'manda-due-diligence-analyzer',
    name: 'M&A Due Diligence Analyzer',
    slug: 'manda-due-diligence-analyzer',
    category: 'Corporate',
    description: 'Review data room documents for risks',
    longDescription: 'Comprehensive review of M&A data room documents including contracts, financials, and corporate records. Identifies material risks, red flags, and deal issues. Perfect for buy-side due diligence.',
    inputFields: [
      {
        name: 'documentType',
        label: 'Document Type',
        type: 'select',
        required: true,
        options: ['Material Contracts', 'Financial Statements', 'Corporate Records', 'Litigation Documents', 'IP Portfolio', 'General Review'],
      },
      {
        name: 'documentText',
        label: 'Document(s) to Review',
        type: 'textarea',
        placeholder: 'Paste documents or summaries here...',
        required: true,
        maxLength: 100000,
        helpText: 'Can analyze multiple documents simultaneously',
      },
      {
        name: 'focusAreas',
        label: 'Focus Areas',
        type: 'multiselect',
        required: false,
        options: ['Financial Risks', 'Legal Liabilities', 'Regulatory Compliance', 'Material Contracts', 'IP Issues', 'Employment Matters'],
      },
    ],
    outputFormat: 'structured',
    complexity: 'very_high',
    estimatedTime: '40-90 seconds',
    requiredTier: 'advanced',
    aiModel: {
      free: 'Not available',
      starter: 'Not available',
      pro: 'Not available',
      advanced: 'Claude Opus',
    },
    samplePrompts: [
      'Review top 10 customer contracts for change of control',
      'Analyze financial statements for red flags',
      'Identify litigation risks in legal documents',
    ],
    relatedTools: ['contract-risk-analyzer', 'contract-clause-extractor'],
    useCases: [
      'M&A buy-side diligence',
      'Investment analysis',
      'Risk assessment',
      'Deal evaluation',
    ],
    icon: '🔍',
  },

  'board-resolution-drafter': {
    id: 'board-resolution-drafter',
    name: 'Board Resolution Drafter',
    slug: 'board-resolution-drafter',
    category: 'Corporate',
    description: 'Generate corporate board resolutions',
    longDescription: 'Create professional board resolutions for corporate actions including officer appointments, contract approvals, and policy adoptions. Includes proper formatting and voting records.',
    inputFields: [
      {
        name: 'resolutionType',
        label: 'Resolution Type',
        type: 'select',
        required: true,
        options: [
          'Officer Appointment',
          'Contract Approval',
          'Policy Adoption',
          'Stock Issuance',
          'Loan Authorization',
          'Real Estate Transaction',
          'Other Corporate Action',
        ],
      },
      {
        name: 'details',
        label: 'Action Details',
        type: 'textarea',
        placeholder: 'Describe the action to be approved...',
        required: true,
        maxLength: 2000,
      },
      {
        name: 'companyName',
        label: 'Company Name',
        type: 'text',
        required: true,
        maxLength: 200,
      },
    ],
    outputFormat: 'text',
    complexity: 'simple',
    estimatedTime: '10-15 seconds',
    requiredTier: 'starter',
    aiModel: {
      free: 'Not available',
      starter: 'Claude Haiku',
      pro: 'Claude Haiku',
      advanced: 'Claude Haiku',
    },
    samplePrompts: [
      'Board resolution appointing new CFO',
      'Resolution approving new vendor contract',
      'Policy adoption for remote work',
    ],
    relatedTools: ['contract-drafter-nda', 'employment-contract-generator'],
    useCases: [
      'Corporate governance',
      'Officer appointments',
      'Contract approvals',
      'Policy changes',
    ],
    icon: '📋',
  },

  'employment-contract-generator': {
    id: 'employment-contract-generator',
    name: 'Employment Contract Generator',
    slug: 'employment-contract-generator',
    category: 'Employment',
    description: 'Create employment agreements',
    longDescription: 'Generate comprehensive employment contracts including compensation, benefits, duties, and termination provisions. Supports at-will, fixed-term, and executive agreements.',
    inputFields: [
      {
        name: 'employmentType',
        label: 'Employment Type',
        type: 'select',
        required: true,
        options: ['At-Will', 'Fixed Term', 'Executive', 'Part-Time', 'Consultant'],
      },
      {
        name: 'employeeName',
        label: 'Employee Name',
        type: 'text',
        required: true,
        maxLength: 200,
      },
      {
        name: 'position',
        label: 'Position/Title',
        type: 'text',
        required: true,
        maxLength: 200,
      },
      {
        name: 'salary',
        label: 'Compensation',
        type: 'text',
        placeholder: 'e.g., $100,000 per year',
        required: true,
        maxLength: 200,
      },
      {
        name: 'benefits',
        label: 'Benefits',
        type: 'textarea',
        placeholder: 'Health insurance, 401k, PTO, etc.',
        required: false,
        maxLength: 1000,
      },
      {
        name: 'jurisdiction',
        label: 'State/Jurisdiction',
        type: 'text',
        placeholder: 'e.g., California',
        required: true,
        maxLength: 100,
      },
    ],
    outputFormat: 'text',
    complexity: 'medium',
    estimatedTime: '20-30 seconds',
    requiredTier: 'pro',
    aiModel: {
      free: 'Not available',
      starter: 'Not available',
      pro: 'Claude Sonnet',
      advanced: 'Claude Opus',
    },
    samplePrompts: [
      'At-will employment for software engineer',
      'Executive agreement for VP of Sales',
      'Part-time consultant agreement',
    ],
    relatedTools: ['contract-drafter-nda', 'termination-letter-drafter'],
    useCases: [
      'New hire onboarding',
      'Executive recruitment',
      'Contractor agreements',
      'Employment terms',
    ],
    icon: '💼',
  },

  'termination-letter-drafter': {
    id: 'termination-letter-drafter',
    name: 'Termination Letter Drafter',
    slug: 'termination-letter-drafter',
    category: 'Employment',
    description: 'Draft legally compliant termination letters',
    longDescription: 'Create professional termination letters with proper legal language, severance terms, and compliance notes. Reduces litigation risk with proper documentation.',
    inputFields: [
      {
        name: 'terminationType',
        label: 'Termination Type',
        type: 'select',
        required: true,
        options: ['Voluntary Resignation', 'Termination With Cause', 'Layoff/Reduction', 'Performance', 'Mutual Agreement'],
      },
      {
        name: 'employeeName',
        label: 'Employee Name',
        type: 'text',
        required: true,
        maxLength: 200,
      },
      {
        name: 'reason',
        label: 'Reason (if applicable)',
        type: 'textarea',
        placeholder: 'Brief reason for termination...',
        required: false,
        maxLength: 1000,
      },
      {
        name: 'severance',
        label: 'Severance Details (if any)',
        type: 'textarea',
        placeholder: 'Severance package details...',
        required: false,
        maxLength: 1000,
      },
      {
        name: 'jurisdiction',
        label: 'State/Jurisdiction',
        type: 'text',
        required: true,
        maxLength: 100,
      },
    ],
    outputFormat: 'text',
    complexity: 'medium',
    estimatedTime: '15-20 seconds',
    requiredTier: 'starter',
    aiModel: {
      free: 'Not available',
      starter: 'Claude Haiku',
      pro: 'Claude Sonnet',
      advanced: 'Claude Sonnet',
    },
    samplePrompts: [
      'Layoff letter with severance package',
      'Termination for cause with documentation',
      'Voluntary resignation acceptance letter',
    ],
    relatedTools: ['employment-contract-generator', 'legal-email-drafter'],
    useCases: [
      'Employee terminations',
      'Layoff documentation',
      'Performance dismissals',
      'Risk mitigation',
    ],
    icon: '📋',
  },

  'patent-prior-art-search': {
    id: 'patent-prior-art-search',
    name: 'Patent Prior Art Search',
    slug: 'patent-prior-art-search',
    category: 'Intellectual Property',
    description: 'AI-powered patent database search',
    longDescription: 'Search patent databases and technical literature for prior art relevant to your invention. Provides similarity scores and patentability assessment. Essential for patent applications.',
    inputFields: [
      {
        name: 'inventionDescription',
        label: 'Invention Description',
        type: 'textarea',
        placeholder: 'Describe the invention in detail...',
        required: true,
        maxLength: 5000,
        helpText: 'Include technical details, novel features, and intended use',
      },
      {
        name: 'claimsText',
        label: 'Proposed Claims (Optional)',
        type: 'textarea',
        placeholder: 'Draft patent claims if available...',
        required: false,
        maxLength: 5000,
      },
      {
        name: 'technologyArea',
        label: 'Technology Area',
        type: 'select',
        required: true,
        options: ['Software', 'Mechanical', 'Electrical', 'Chemical', 'Biotech', 'Medical Device', 'Other'],
      },
    ],
    outputFormat: 'structured',
    complexity: 'very_high',
    estimatedTime: '45-90 seconds',
    requiredTier: 'advanced',
    aiModel: {
      free: 'Not available',
      starter: 'Not available',
      pro: 'Not available',
      advanced: 'Claude Opus',
    },
    samplePrompts: [
      'Search for prior art on mobile app feature',
      'Find similar patents for mechanical device',
      'Research chemical compound patentability',
    ],
    relatedTools: ['legal-research-assistant', 'contract-drafter-nda'],
    useCases: [
      'Patent applications',
      'Novelty assessment',
      'Patent prosecution',
      'Freedom to operate',
    ],
    icon: '💡',
  },

  'client-status-update': {
    id: 'client-status-update',
    name: 'Client Status Update Generator',
    slug: 'client-status-update',
    category: 'Client Communication',
    description: 'Professional client update letters',
    longDescription: 'Generate client-friendly status update letters for ongoing matters. Translate legal developments into plain language while maintaining professionalism.',
    inputFields: [
      {
        name: 'matterType',
        label: 'Matter Type',
        type: 'select',
        required: true,
        options: ['Litigation', 'Transaction', 'Regulatory', 'Corporate', 'Estate Planning', 'Other'],
      },
      {
        name: 'recentDevelopments',
        label: 'Recent Developments',
        type: 'textarea',
        placeholder: 'What has happened since last update?',
        required: true,
        maxLength: 3000,
      },
      {
        name: 'nextSteps',
        label: 'Next Steps',
        type: 'textarea',
        placeholder: 'What actions are planned?',
        required: true,
        maxLength: 2000,
      },
      {
        name: 'tone',
        label: 'Tone',
        type: 'select',
        required: true,
        options: ['Optimistic', 'Neutral', 'Cautious', 'Urgent'],
      },
    ],
    outputFormat: 'text',
    complexity: 'simple',
    estimatedTime: '10-15 seconds',
    requiredTier: 'free',
    aiModel: {
      free: 'Gemini 1.5 Flash',
      starter: 'Claude Haiku',
      pro: 'Claude Haiku',
      advanced: 'Claude Haiku',
    },
    samplePrompts: [
      'Update client on discovery progress',
      'Inform client about settlement negotiations',
      'Report on transaction closing timeline',
    ],
    relatedTools: ['legal-email-drafter', 'case-law-summarizer'],
    useCases: [
      'Client communication',
      'Case updates',
      'Relationship building',
      'Transparency',
    ],
    icon: '📨',
  },

  'lease-agreement-analyzer': {
    id: 'lease-agreement-analyzer',
    name: 'Lease Agreement Analyzer',
    slug: 'lease-agreement-analyzer',
    category: 'Real Estate',
    description: 'Review residential/commercial leases',
    longDescription: 'Comprehensive analysis of lease agreements identifying key terms, risks, and unusual provisions. Supports both residential and commercial leases.',
    inputFields: [
      {
        name: 'leaseType',
        label: 'Lease Type',
        type: 'select',
        required: true,
        options: ['Residential', 'Commercial', 'Industrial', 'Retail', 'Office'],
      },
      {
        name: 'leaseText',
        label: 'Lease Agreement',
        type: 'textarea',
        placeholder: 'Paste lease agreement here...',
        required: true,
        maxLength: 50000,
      },
      {
        name: 'perspective',
        label: 'Review From Perspective Of',
        type: 'select',
        required: true,
        options: ['Landlord', 'Tenant', 'Neutral'],
      },
    ],
    outputFormat: 'structured',
    complexity: 'medium',
    estimatedTime: '20-35 seconds',
    requiredTier: 'pro',
    aiModel: {
      free: 'Not available',
      starter: 'Not available',
      pro: 'Claude Sonnet',
      advanced: 'Claude Opus',
    },
    samplePrompts: [
      'Review commercial lease for tenant',
      'Analyze residential lease for red flags',
      'Check retail lease renewal terms',
    ],
    relatedTools: ['contract-risk-analyzer', 'contract-summary-generator'],
    useCases: [
      'Lease negotiation',
      'Tenant representation',
      'Property management',
      'Risk assessment',
    ],
    icon: '🏢',
  },

  'legal-research-assistant': {
    id: 'legal-research-assistant',
    name: 'Legal Research Assistant',
    slug: 'legal-research-assistant',
    category: 'Legal Research',
    description: 'Natural language queries to search case law, statutes, regulations',
    longDescription: 'AI-powered legal research using natural language queries. Search 50+ years of case law, statutes, and regulations across all jurisdictions. Get comprehensive answers with proper citations.',
    inputFields: [
      {
        name: 'query',
        label: 'Research Question',
        type: 'textarea',
        placeholder: 'Ask your legal question in plain language...',
        required: true,
        maxLength: 2000,
        helpText: 'Be specific about jurisdiction, time period, and legal issues',
      },
      {
        name: 'jurisdiction',
        label: 'Jurisdiction',
        type: 'text',
        placeholder: 'e.g., California, 9th Circuit, Federal, All',
        required: true,
        maxLength: 100,
      },
      {
        name: 'dateRange',
        label: 'Date Range (Optional)',
        type: 'select',
        required: false,
        options: ['Last Year', 'Last 5 Years', 'Last 10 Years', 'Since 2000', 'All Time'],
      },
      {
        name: 'focusArea',
        label: 'Focus On',
        type: 'select',
        required: false,
        options: ['Case Law', 'Statutes', 'Regulations', 'All Sources'],
      },
    ],
    outputFormat: 'markdown',
    complexity: 'high',
    estimatedTime: '25-45 seconds',
    requiredTier: 'pro',
    aiModel: {
      free: 'Not available',
      starter: 'Not available',
      pro: 'Claude Sonnet',
      advanced: 'Claude Opus',
    },
    samplePrompts: [
      'California employment discrimination standards 2020-2024',
      'Federal sentencing guidelines for white collar crimes',
      'Recent Supreme Court decisions on qualified immunity',
    ],
    relatedTools: ['case-law-summarizer', 'legal-memo-writer', 'legal-issue-spotter'],
    useCases: [
      'Legal research',
      'Brief writing',
      'Case analysis',
      'Legal strategy',
    ],
    icon: '🔍',
  },
}

// Helper function to get tool config
export function getToolConfig(slug: string): ToolConfig | undefined {
  return toolConfigs[slug]
}

// Get all tool configs
export function getAllToolConfigs(): ToolConfig[] {
  return Object.values(toolConfigs)
}

// Get tools by category
export function getToolsByCategory(category: string): ToolConfig[] {
  return Object.values(toolConfigs).filter(tool => tool.category === category)
}

// Get tools by tier
export function getToolsByTier(tier: 'free' | 'starter' | 'pro' | 'advanced'): ToolConfig[] {
  return Object.values(toolConfigs).filter(tool => {
    switch (tier) {
      case 'free':
        return tool.requiredTier === 'free'
      case 'starter':
        return ['free', 'starter'].includes(tool.requiredTier)
      case 'pro':
        return ['free', 'starter', 'pro'].includes(tool.requiredTier)
      case 'advanced':
        return true
      default:
        return false
    }
  })
}
