import { NextRequest, NextResponse } from 'next/server'
import { cookies } from 'next/headers'
import { getSessionUser } from '@/lib/auth'
import { prisma } from '@/lib/db'
import { createClioClient } from '@/lib/integrations/clio/clio-client'

/**
 * POST /api/integrations/clio/documents
 * Save a document to Clio matter
 */
export async function POST(request: NextRequest) {
  try {
    const cookieStore = await cookies()
    const sessionToken = cookieStore.get('session')?.value

    if (!sessionToken) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
    }

    const user = await getSessionUser(sessionToken)
    if (!user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
    }

    // Get Clio connection
    const connection = await prisma.clioConnection.findFirst({
      where: { userId: user.id },
    })

    if (!connection || connection.status !== 'active') {
      return NextResponse.json(
        { error: 'Clio account not connected' },
        { status: 400 }
      )
    }

    // Check if token is expired
    if (connection.expiresAt && connection.expiresAt < new Date()) {
      return NextResponse.json(
        { error: 'Clio token expired' },
        { status: 401 }
      )
    }

    const body = await request.json()
    const { matterId, documentName, content, description, toolRunId } = body

    if (!matterId || !documentName || !content) {
      return NextResponse.json(
        { error: 'Matter ID, document name, and content are required' },
        { status: 400 }
      )
    }

    // Create Clio client
    const clioClient = createClioClient({
      accessToken: connection.accessToken,
    })

    // Convert content to buffer (assuming it's text content)
    const contentBuffer = Buffer.from(content, 'utf-8')
    const filename = documentName.endsWith('.txt') ? documentName : `${documentName}.txt`

    // Upload document to Clio
    const response = await clioClient.uploadDocument({
      matter_id: parseInt(matterId),
      name: documentName,
      description: description || `Document generated by Frith AI${toolRunId ? ` (Tool Run: ${toolRunId})` : ''}`,
      file: contentBuffer,
      filename,
      contentType: 'text/plain',
    })

    // Create activity log
    await prisma.activityLog.create({
      data: {
        userId: user.id,
        action: 'exported',
        targetType: 'document',
        targetId: response.data.id.toString(),
        description: `Saved document "${documentName}" to Clio matter ${matterId}`,
        metadata: {
          clioDocumentId: response.data.id,
          clioMatterId: matterId,
          documentName,
          toolRunId,
          contentLength: content.length,
        },
      },
    })

    return NextResponse.json({
      success: true,
      clioDocument: response.data,
      message: 'Document saved to Clio successfully',
    })
  } catch (error) {
    console.error('[Clio] Save document error:', error)
    
    if (error instanceof Error && error.message.includes('Unauthorized')) {
      // Token might be expired, mark connection as expired
      const cookieStore = await cookies()
      const sessionUser = await getSessionUser(cookieStore.get('session')?.value || '')
      if (sessionUser?.id) {
        await prisma.clioConnection.updateMany({
          where: { userId: sessionUser.id },
          data: { status: 'expired' },
        })
      }
      
      return NextResponse.json(
        { error: 'Clio token expired' },
        { status: 401 }
      )
    }

    return NextResponse.json(
      { error: 'Failed to save document to Clio' },
      { status: 500 }
    )
  }
}

/**
 * GET /api/integrations/clio/documents
 * List documents from connected Clio account
 */
export async function GET(request: NextRequest) {
  try {
    const cookieStore = await cookies()
    const sessionToken = cookieStore.get('session')?.value

    if (!sessionToken) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
    }

    const user = await getSessionUser(sessionToken)
    if (!user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
    }

    // Get Clio connection
    const connection = await prisma.clioConnection.findFirst({
      where: { userId: user.id },
    })

    if (!connection || connection.status !== 'active') {
      return NextResponse.json(
        { error: 'Clio account not connected' },
        { status: 400 }
      )
    }

    // Check if token is expired
    if (connection.expiresAt && connection.expiresAt < new Date()) {
      return NextResponse.json(
        { error: 'Clio token expired' },
        { status: 401 }
      )
    }

    // Parse query parameters
    const { searchParams } = new URL(request.url)
    const limit = parseInt(searchParams.get('limit') || '50')
    const offset = parseInt(searchParams.get('offset') || '0')
    const matterId = searchParams.get('matter_id')

    // Create Clio client and fetch documents
    const clioClient = createClioClient({
      accessToken: connection.accessToken,
    })

    const response = await clioClient.getDocuments({
      limit: Math.min(limit, 100), // Cap at 100
      offset,
      matter_id: matterId ? parseInt(matterId) : undefined,
    })

    return NextResponse.json({
      documents: response.data,
      pagination: {
        limit,
        offset,
        total: response.data.length,
      },
    })
  } catch (error) {
    console.error('[Clio] Get documents error:', error)
    
    if (error instanceof Error && error.message.includes('Unauthorized')) {
      // Token might be expired, mark connection as expired
      const cookieStore = await cookies()
      const sessionUser = await getSessionUser(cookieStore.get('session')?.value || '')
      if (sessionUser?.id) {
        await prisma.clioConnection.updateMany({
          where: { userId: sessionUser.id },
          data: { status: 'expired' },
        })
      }
      
      return NextResponse.json(
        { error: 'Clio token expired' },
        { status: 401 }
      )
    }

    return NextResponse.json(
      { error: 'Failed to fetch documents' },
      { status: 500 }
    )
  }
}
