/**
 * Wave 3 Practice Management & Client Tools (25 tools)
 */

export const WAVE3_PRACTICE_TOOLS = [
  {
    name: 'Client Communication Logger',
    slug: 'client-communication-logger',
    description: 'Log and summarize client communications',
    category: 'client-management',
    inputType: 'text',
    outputType: 'text',
    pricingTier: 'pro',
    promptTemplate: 'Summarize client communication:\n\n{{input}}\n\nExtract key points, action items, and follow-ups.',
    systemPrompt: 'You are a legal practice management assistant.',
    maxTokens: 2000,
    temperature: 0.5,
    wave: 3,
  },
  {
    name: 'Case Status Updater',
    slug: 'case-status-updater',
    description: 'Generate case status updates for clients',
    category: 'client-management',
    inputType: 'structured',
    outputType: 'text',
    pricingTier: 'pro',
    promptTemplate: 'Generate case status update:\n\n{{input}}\n\nProvide clear summary for client.',
    systemPrompt: 'You are a legal communications specialist.',
    maxTokens: 2000,
    temperature: 0.6,
    wave: 3,
  },
  {
    name: 'Fee Agreement Generator',
    slug: 'fee-agreement-generator',
    description: 'Generate fee agreements and retainer letters',
    category: 'billing',
    inputType: 'structured',
    outputType: 'document',
    pricingTier: 'pro',
    promptTemplate: 'Generate fee agreement:\n\n{{input}}\n\nInclude scope, fees, billing terms, and termination.',
    systemPrompt: 'You are a legal practice management expert.',
    maxTokens: 4000,
    temperature: 0.4,
    wave: 3,
  },
  {
    name: 'Invoice Narrative Generator',
    slug: 'invoice-narrative-generator',
    description: 'Generate professional invoice narratives from time entries',
    category: 'billing',
    inputType: 'text',
    outputType: 'text',
    pricingTier: 'pro',
    promptTemplate: 'Generate invoice narratives:\n\n{{input}}\n\nCreate clear, professional billing descriptions.',
    systemPrompt: 'You are a legal billing specialist.',
    maxTokens: 3000,
    temperature: 0.5,
    wave: 3,
  },
  {
    name: 'LEDES Bill Formatter',
    slug: 'ledes-bill-formatter',
    description: 'Format invoices in LEDES billing format',
    category: 'billing',
    inputType: 'structured',
    outputType: 'document',
    pricingTier: 'professional',
    promptTemplate: 'Format LEDES bill:\n\n{{input}}\n\nGenerate LEDES-compliant invoice.',
    systemPrompt: 'You are a legal billing expert on LEDES format.',
    maxTokens: 4000,
    temperature: 0.3,
    wave: 3,
  },
  {
    name: 'Trust Account Reconciler',
    slug: 'trust-account-reconciler',
    description: 'Reconcile client trust accounts and IOLTA',
    category: 'billing',
    inputType: 'structured',
    outputType: 'text',
    pricingTier: 'professional',
    promptTemplate: 'Reconcile trust account:\n\n{{input}}\n\nProvide reconciliation and compliance check.',
    systemPrompt: 'You are a legal accounting expert.',
    maxTokens: 3000,
    temperature: 0.3,
    wave: 3,
  },
  {
    name: 'Matter Profitability Analyzer',
    slug: 'matter-profitability-analyzer',
    description: 'Analyze matter profitability and realization rates',
    category: 'analytics',
    inputType: 'structured',
    outputType: 'json',
    pricingTier: 'professional',
    promptTemplate: 'Analyze matter profitability:\n\n{{input}}\n\nCalculate realization, utilization, and margins.',
    systemPrompt: 'You are a legal finance analyst.',
    maxTokens: 3000,
    temperature: 0.4,
    wave: 3,
  },
  {
    name: 'Attorney Utilization Report',
    slug: 'attorney-utilization-report',
    description: 'Generate attorney utilization and productivity reports',
    category: 'analytics',
    inputType: 'structured',
    outputType: 'document',
    pricingTier: 'professional',
    promptTemplate: 'Generate utilization report:\n\n{{input}}\n\nAnalyze billable hours and productivity.',
    systemPrompt: 'You are a legal practice analytics expert.',
    maxTokens: 4000,
    temperature: 0.4,
    wave: 3,
  },
  {
    name: 'Client Satisfaction Survey Generator',
    slug: 'client-satisfaction-survey-generator',
    description: 'Generate client satisfaction surveys',
    category: 'client-management',
    inputType: 'structured',
    outputType: 'document',
    pricingTier: 'pro',
    promptTemplate: 'Generate client survey:\n\n{{input}}\n\nCreate professional satisfaction survey.',
    systemPrompt: 'You are a client relations specialist.',
    maxTokens: 2000,
    temperature: 0.6,
    wave: 3,
  },
  {
    name: 'New Client Onboarding Checklist',
    slug: 'new-client-onboarding-checklist',
    description: 'Generate new client onboarding checklists',
    category: 'client-management',
    inputType: 'structured',
    outputType: 'document',
    pricingTier: 'pro',
    promptTemplate: 'Generate onboarding checklist:\n\n{{input}}\n\nCreate comprehensive client onboarding steps.',
    systemPrompt: 'You are a legal practice management expert.',
    maxTokens: 3000,
    temperature: 0.5,
    wave: 3,
  },
  {
    name: 'Document Retention Policy Drafter',
    slug: 'document-retention-policy-drafter',
    description: 'Draft document retention and destruction policies',
    category: 'knowledge-management',
    inputType: 'structured',
    outputType: 'document',
    pricingTier: 'professional',
    promptTemplate: 'Draft retention policy:\n\n{{input}}\n\nInclude retention periods and destruction procedures.',
    systemPrompt: 'You are a records management expert.',
    maxTokens: 4000,
    temperature: 0.4,
    wave: 3,
  },
  {
    name: 'Legal Hold Notice Generator',
    slug: 'legal-hold-notice-generator',
    description: 'Generate litigation hold notices',
    category: 'litigation-support',
    inputType: 'structured',
    outputType: 'document',
    pricingTier: 'professional',
    promptTemplate: 'Generate legal hold notice:\n\n{{input}}\n\nCreate comprehensive preservation notice.',
    systemPrompt: 'You are an e-discovery expert.',
    maxTokens: 3000,
    temperature: 0.4,
    wave: 3,
  },
  {
    name: 'Firm Marketing Content Generator',
    slug: 'firm-marketing-content-generator',
    description: 'Generate law firm marketing content',
    category: 'knowledge-management',
    inputType: 'structured',
    outputType: 'text',
    pricingTier: 'pro',
    promptTemplate: 'Generate marketing content:\n\n{{input}}\n\nCreate professional law firm content.',
    systemPrompt: 'You are a legal marketing specialist.',
    maxTokens: 3000,
    temperature: 0.7,
    wave: 3,
  },
  {
    name: 'Attorney Bio Writer',
    slug: 'attorney-bio-writer',
    description: 'Write professional attorney biographies',
    category: 'knowledge-management',
    inputType: 'structured',
    outputType: 'text',
    pricingTier: 'pro',
    promptTemplate: 'Write attorney bio:\n\n{{input}}\n\nCreate professional biography.',
    systemPrompt: 'You are a legal marketing writer.',
    maxTokens: 2000,
    temperature: 0.6,
    wave: 3,
  },
  {
    name: 'CLE Presentation Outliner',
    slug: 'cle-presentation-outliner',
    description: 'Create CLE presentation outlines',
    category: 'knowledge-management',
    inputType: 'structured',
    outputType: 'document',
    pricingTier: 'pro',
    promptTemplate: 'Create CLE outline:\n\n{{input}}\n\nGenerate educational presentation outline.',
    systemPrompt: 'You are a legal education specialist.',
    maxTokens: 4000,
    temperature: 0.6,
    wave: 3,
  },
  {
    name: 'Legal Blog Post Generator',
    slug: 'legal-blog-post-generator',
    description: 'Generate legal blog posts and articles',
    category: 'knowledge-management',
    inputType: 'structured',
    outputType: 'text',
    pricingTier: 'pro',
    promptTemplate: 'Generate blog post:\n\n{{input}}\n\nCreate informative legal article.',
    systemPrompt: 'You are a legal content writer.',
    maxTokens: 4000,
    temperature: 0.7,
    wave: 3,
  },
  {
    name: 'Case Intake Screener',
    slug: 'case-intake-screener',
    description: 'Screen potential cases for viability',
    category: 'client-management',
    inputType: 'text',
    outputType: 'json',
    pricingTier: 'professional',
    promptTemplate: 'Screen case intake:\n\n{{input}}\n\nAnalyze viability, conflicts, and recommendations.',
    systemPrompt: 'You are a legal intake specialist.',
    maxTokens: 3000,
    temperature: 0.5,
    wave: 3,
  },
  {
    name: 'Statute of Limitations Calculator',
    slug: 'statute-of-limitations-calculator',
    description: 'Calculate statutes of limitations by claim type',
    category: 'legal-research',
    inputType: 'structured',
    outputType: 'json',
    pricingTier: 'pro',
    promptTemplate: 'Calculate SOL:\n\n{{input}}\n\nProvide limitations periods and tolling analysis.',
    systemPrompt: 'You are a legal research expert on limitations.',
    maxTokens: 3000,
    temperature: 0.3,
    wave: 3,
  },
  {
    name: 'Court Filing Fee Calculator',
    slug: 'court-filing-fee-calculator',
    description: 'Calculate court filing fees by jurisdiction',
    category: 'billing',
    inputType: 'structured',
    outputType: 'json',
    pricingTier: 'pro',
    promptTemplate: 'Calculate filing fees:\n\n{{input}}\n\nProvide fee amounts and requirements.',
    systemPrompt: 'You are a court procedures expert.',
    maxTokens: 2000,
    temperature: 0.3,
    wave: 3,
  },
  {
    name: 'Service of Process Tracker',
    slug: 'service-of-process-tracker',
    description: 'Track and verify service of process',
    category: 'litigation-support',
    inputType: 'structured',
    outputType: 'text',
    pricingTier: 'pro',
    promptTemplate: 'Track service of process:\n\n{{input}}\n\nVerify service requirements and deadlines.',
    systemPrompt: 'You are a litigation support specialist.',
    maxTokens: 2000,
    temperature: 0.4,
    wave: 3,
  },
  {
    name: 'Court Rules Lookup',
    slug: 'court-rules-lookup',
    description: 'Look up court rules and local procedures',
    category: 'legal-research',
    inputType: 'text',
    outputType: 'text',
    pricingTier: 'pro',
    promptTemplate: 'Look up court rules:\n\n{{input}}\n\nProvide applicable rules and procedures.',
    systemPrompt: 'You are a court procedures expert.',
    maxTokens: 3000,
    temperature: 0.4,
    wave: 3,
  },
  {
    name: 'Docket Entry Analyzer',
    slug: 'docket-entry-analyzer',
    description: 'Analyze court docket entries and history',
    category: 'litigation-support',
    inputType: 'text',
    outputType: 'text',
    pricingTier: 'professional',
    promptTemplate: 'Analyze docket:\n\n{{input}}\n\nSummarize case history and upcoming deadlines.',
    systemPrompt: 'You are a litigation analyst.',
    maxTokens: 3000,
    temperature: 0.5,
    wave: 3,
  },
  {
    name: 'Expert Deposition Prep',
    slug: 'expert-deposition-prep',
    description: 'Prepare for expert witness depositions',
    category: 'litigation-support',
    inputType: 'text',
    outputType: 'document',
    pricingTier: 'professional',
    promptTemplate: 'Prepare expert deposition:\n\n{{input}}\n\nGenerate question outlines and strategy.',
    systemPrompt: 'You are a litigation expert on depositions.',
    maxTokens: 5000,
    temperature: 0.6,
    wave: 3,
  },
  {
    name: 'Damages Calculation Tool',
    slug: 'damages-calculation-tool',
    description: 'Calculate damages for various claim types',
    category: 'litigation-support',
    inputType: 'structured',
    outputType: 'json',
    pricingTier: 'professional',
    promptTemplate: 'Calculate damages:\n\n{{input}}\n\nProvide economic and non-economic calculations.',
    systemPrompt: 'You are a damages expert.',
    maxTokens: 4000,
    temperature: 0.4,
    wave: 3,
  },
  {
    name: 'Mediation Brief Drafter',
    slug: 'mediation-brief-drafter',
    description: 'Draft mediation briefs and position statements',
    category: 'litigation-support',
    inputType: 'text',
    outputType: 'document',
    pricingTier: 'professional',
    promptTemplate: 'Draft mediation brief:\n\n{{input}}\n\nCreate persuasive position statement.',
    systemPrompt: 'You are an ADR specialist.',
    maxTokens: 5000,
    temperature: 0.6,
    wave: 3,
  },
]
