/**
 * Wave 2 Additional Corporate & Commercial Tools (5 tools)
 */

export const WAVE2_CORPORATE_TOOLS = [
  {
    name: 'Securities Offering Memo Drafter',
    slug: 'securities-offering-memo-drafter',
    description: 'Draft private placement memorandums',
    category: 'corporate-law',
    inputType: 'structured',
    outputType: 'document',
    pricingTier: 'enterprise',
    promptTemplate: 'Draft PPM:\n\n{{input}}\n\nInclude executive summary, risks, use of proceeds, and subscription.',
    systemPrompt: 'You are a securities attorney on private placements.',
    maxTokens: 8000,
    temperature: 0.4,
    wave: 2,
  },
  {
    name: 'Board Resolution Drafter',
    slug: 'board-resolution-drafter',
    description: 'Draft corporate board resolutions',
    category: 'corporate-law',
    inputType: 'structured',
    outputType: 'document',
    pricingTier: 'pro',
    promptTemplate: 'Draft board resolution:\n\n{{input}}\n\nInclude recitals, resolved clauses, and certification.',
    systemPrompt: 'You are a corporate attorney on governance.',
    maxTokens: 3000,
    temperature: 0.4,
    wave: 2,
  },
  {
    name: 'Shareholder Agreement Drafter',
    slug: 'shareholder-agreement-drafter',
    description: 'Draft shareholder agreements for closely held companies',
    category: 'corporate-law',
    inputType: 'structured',
    outputType: 'document',
    pricingTier: 'professional',
    promptTemplate: 'Draft shareholder agreement:\n\n{{input}}\n\nInclude transfer restrictions, voting, and buy-sell.',
    systemPrompt: 'You are a corporate attorney on closely held companies.',
    maxTokens: 6000,
    temperature: 0.4,
    wave: 2,
  },
  {
    name: 'Operating Agreement Drafter',
    slug: 'operating-agreement-drafter',
    description: 'Draft LLC operating agreements',
    category: 'corporate-law',
    inputType: 'structured',
    outputType: 'document',
    pricingTier: 'professional',
    promptTemplate: 'Draft LLC operating agreement:\n\n{{input}}\n\nInclude contributions, management, and distributions.',
    systemPrompt: 'You are a business attorney on LLC formation.',
    maxTokens: 6000,
    temperature: 0.4,
    wave: 2,
  },
  {
    name: 'Franchise Agreement Analyzer',
    slug: 'franchise-agreement-analyzer',
    description: 'Analyze franchise agreements and FDD disclosures',
    category: 'contract-review',
    inputType: 'document',
    outputType: 'text',
    pricingTier: 'professional',
    promptTemplate: 'Analyze franchise agreement:\n\n{{input}}\n\nReview territory, fees, and FTC compliance.',
    systemPrompt: 'You are a franchise law expert.',
    maxTokens: 5000,
    temperature: 0.5,
    wave: 2,
  },
]
