/**
 * Wave 3 Operations & Management Tools (14 tools)
 */

export const WAVE3_OPERATIONS_TOOLS = [
  {
    name: 'Firm KPI Dashboard Generator',
    slug: 'firm-kpi-dashboard-generator',
    description: 'Generate a firm-wide KPI dashboard with utilization, realization, and profitability metrics.',
    category: 'analytics',
    inputType: 'structured',
    outputType: 'document',
    pricingTier: 'enterprise',
    promptTemplate: `You are a legal operations analyst. Using the following firm metrics and configuration, generate a clear KPI dashboard summary.\n\nInput data:\n{{input}}\n\nProvide:\n1. Executive summary\n2. Key metrics (utilization, realization, profitability)\n3. Trend highlights\n4. Practice-area breakdown\n5. Recommended focus areas for the next quarter.`,
    systemPrompt: 'You are an expert in law firm operations and financial analytics.',
    maxTokens: 4500,
    temperature: 0.4,
    wave: 3,
  },
  {
    name: 'Staffing Plan Optimizer',
    slug: 'staffing-plan-optimizer',
    description: 'Optimize staffing plans across matters and practice groups based on workload and experience.',
    category: 'collaborative',
    inputType: 'structured',
    outputType: 'json',
    pricingTier: 'professional',
    promptTemplate: `You are a legal project management expert. Analyze the following matters, deadlines, and attorney profiles to propose an optimized staffing plan.\n\nInput:\n{{input}}\n\nReturn:\n- Recommended staffing assignments per matter\n- Estimated hours per role\n- Over/under-utilization flags\n- Risks and mitigation suggestions.`,
    systemPrompt: 'You specialize in law firm resource planning and staffing optimization.',
    maxTokens: 4000,
    temperature: 0.5,
    wave: 3,
  },
  {
    name: 'Outside Counsel Guidelines Analyzer',
    slug: 'outside-counsel-guidelines-analyzer',
    description: 'Analyze outside counsel guidelines for billing, staffing, and matter management requirements.',
    category: 'contract-review',
    inputType: 'document',
    outputType: 'text',
    pricingTier: 'professional',
    promptTemplate: `Review these Outside Counsel Guidelines (OCGs) and summarize key requirements.\n\nGuidelines:\n{{input}}\n\nProvide:\n1. Billing rules and restrictions\n2. Staffing requirements and approval thresholds\n3. Reporting and budgeting expectations\n4. Disallowed activities/charges\n5. Implementation checklist for the firm.`,
    systemPrompt: 'You are an in-house legal operations expert reviewing outside counsel guidelines.',
    maxTokens: 5000,
    temperature: 0.5,
    wave: 3,
  },
  {
    name: 'Billing Guidelines Compliance Checker',
    slug: 'billing-guidelines-compliance-checker',
    description: 'Check time entries and invoices against client billing guidelines.',
    category: 'billing',
    inputType: 'structured',
    outputType: 'json',
    pricingTier: 'professional',
    promptTemplate: `You are a legal billing compliance specialist. Compare the following time entries against the provided billing guidelines.\n\nBilling guidelines:\n{{input.billingGuidelines}}\n\nTime entries:\n{{input.timeEntries}}\n\nReturn a JSON report with:\n- entryId\n- compliant (true/false)\n- issues[]\n- suggested adjustments.`,
    systemPrompt: 'You specialize in legal billing guidelines and e-billing compliance.',
    maxTokens: 4000,
    temperature: 0.4,
    wave: 3,
  },
  {
    name: 'Legal Ops Project Roadmap Builder',
    slug: 'legal-ops-project-roadmap-builder',
    description: 'Build a prioritized roadmap of legal operations initiatives for the next 12 months.',
    category: 'collaborative',
    inputType: 'text',
    outputType: 'document',
    pricingTier: 'enterprise',
    promptTemplate: `You are a legal operations consultant. Based on the firm profile and current challenges described below, create a 12-month legal operations roadmap.\n\nFirm context:\n{{input}}\n\nProvide:\n1. Top 8–12 initiatives, grouped by quarter\n2. Owner and stakeholders for each initiative\n3. Expected impact and rough effort level\n4. Dependencies and risks\n5. Quick wins to tackle first.`,
    systemPrompt: 'You design strategic roadmaps for modern legal departments and law firms.',
    maxTokens: 5000,
    temperature: 0.6,
    wave: 3,
  },
  {
    name: 'Knowledge Gap Analyzer',
    slug: 'knowledge-gap-analyzer',
    description: 'Analyze a firm’s knowledge assets to identify gaps and high-value content opportunities.',
    category: 'knowledge-management',
    inputType: 'structured',
    outputType: 'text',
    pricingTier: 'professional',
    promptTemplate: `You are a knowledge management expert. Analyze the following inventory of templates, playbooks, and precedents.\n\nKnowledge inventory:\n{{input}}\n\nProvide:\n1. Areas with strong coverage\n2. Critical gaps by practice area\n3. Top 5–10 content pieces to create next\n4. Suggested owners and timelines.`,
    systemPrompt: 'You specialize in legal KM programs and content strategy.',
    maxTokens: 4000,
    temperature: 0.5,
    wave: 3,
  },
  {
    name: 'Legal Tech ROI Calculator',
    slug: 'legal-tech-roi-calculator',
    description: 'Estimate ROI for legal technology investments using time savings and risk reduction.',
    category: 'analytics',
    inputType: 'structured',
    outputType: 'json',
    pricingTier: 'professional',
    promptTemplate: `You are a legal operations financial analyst. Using the following assumptions, estimate ROI for a legal tech project.\n\nInputs:\n{{input}}\n\nCalculate and return as JSON:\n- annualTimeSavingsHours\n- annualCostSavings\n- implementationCost\n- paybackPeriodMonths\n- threeYearNPV\n- commentary.`,
    systemPrompt: 'You specialize in building ROI models for legal technology projects.',
    maxTokens: 3500,
    temperature: 0.4,
    wave: 3,
  },
  {
    name: 'Outside Counsel Scorecard Generator',
    slug: 'outside-counsel-scorecard-generator',
    description: 'Generate performance scorecards for outside counsel based on KPIs and feedback.',
    category: 'analytics',
    inputType: 'structured',
    outputType: 'document',
    pricingTier: 'enterprise',
    promptTemplate: `You are an in-house legal operations manager. Using the following matter data and KPIs, generate a performance scorecard for outside counsel.\n\nInput data:\n{{input}}\n\nProvide for each firm:\n1. Overall rating (1–5)\n2. Performance on budget, quality, responsiveness, diversity, innovation\n3. Key strengths and weaknesses\n4. Recommendations (continue, expand, remediate, replace).`,
    systemPrompt: 'You evaluate outside counsel performance using quantitative and qualitative data.',
    maxTokens: 5000,
    temperature: 0.5,
    wave: 3,
  },
  {
    name: 'Pro Bono Program Planner',
    slug: 'pro-bono-program-planner',
    description: 'Design a structured pro bono program with matter types, partners, and policies.',
    category: 'specialized-areas',
    inputType: 'text',
    outputType: 'document',
    pricingTier: 'pro',
    promptTemplate: `You are a pro bono program director for a large law firm. Based on the firm profile and goals below, design a pro bono program.\n\nFirm info:\n{{input}}\n\nProvide:\n1. Priority pro bono focus areas\n2. Partner organizations and referral sources\n3. Intake and conflicts workflow\n4. Supervision and training model\n5. Recognition and credit policies.`,
    systemPrompt: 'You specialize in designing pro bono programs for law firms.',
    maxTokens: 4500,
    temperature: 0.6,
    wave: 3,
  },
  {
    name: 'ESG Policy Drafter',
    slug: 'esg-policy-drafter',
    description: 'Draft ESG and sustainability policies tailored to a client’s risk profile and industry.',
    category: 'compliance',
    inputType: 'structured',
    outputType: 'document',
    pricingTier: 'enterprise',
    promptTemplate: `You are an ESG and sustainability counsel. Draft an ESG policy for the organization described below.\n\nOrganization profile and goals:\n{{input}}\n\nInclude sections on:\n1. Environmental commitments\n2. Social responsibility and DEI\n3. Governance and ethics\n4. Reporting and metrics\n5. Oversight and accountability.`,
    systemPrompt: 'You are an expert in ESG, sustainability, and corporate governance.',
    maxTokens: 6000,
    temperature: 0.5,
    wave: 3,
  },
  {
    name: 'Data Retention Schedule Generator',
    slug: 'data-retention-schedule-generator',
    description: 'Generate a data retention schedule aligned with legal, regulatory, and business requirements.',
    category: 'knowledge-management',
    inputType: 'structured',
    outputType: 'document',
    pricingTier: 'professional',
    promptTemplate: `You are an information governance specialist. Using the following jurisdictions, practice areas, and data types, create a data retention schedule.\n\nInputs:\n{{input}}\n\nProvide a table-like schedule with:\n- dataType\n- system/location\n- retentionPeriod\n- legal/regulatory basis\n- disposition method.`,
    systemPrompt: 'You design defensible data retention schedules for legal and compliance teams.',
    maxTokens: 5000,
    temperature: 0.4,
    wave: 3,
  },
  {
    name: 'Business Continuity Playbook Drafter',
    slug: 'business-continuity-playbook-drafter',
    description: 'Draft a legal department business continuity and incident response playbook.',
    category: 'compliance',
    inputType: 'text',
    outputType: 'document',
    pricingTier: 'enterprise',
    promptTemplate: `You are a risk and resilience advisor for corporate legal departments. Draft a business continuity and incident response playbook based on the organization description below.\n\nContext:\n{{input}}\n\nInclude:\n1. Roles and responsibilities\n2. Incident classification and escalation\n3. Communication plans (internal/external)\n4. Legal hold and evidence preservation\n5. Recovery and post-incident review steps.`,
    systemPrompt: 'You specialize in business continuity and incident response for legal teams.',
    maxTokens: 6500,
    temperature: 0.5,
    wave: 3,
  },
  {
    name: 'Outside Counsel Panel RFP Generator',
    slug: 'outside-counsel-panel-rfp-generator',
    description: 'Generate RFP documentation for creating or refreshing an outside counsel panel.',
    category: 'compliance',
    inputType: 'structured',
    outputType: 'document',
    pricingTier: 'enterprise',
    promptTemplate: `You are an in-house counsel leading an outside counsel panel refresh. Draft an RFP document based on the parameters below.\n\nRFP parameters:\n{{input}}\n\nInclude sections on:\n1. Scope of services and practice areas\n2. Firm information and diversity metrics\n3. Staffing model and key personnel\n4. Pricing and AFAs\n5. Technology and innovation\n6. Evaluation criteria and timeline.`,
    systemPrompt: 'You design RFPs for corporate legal departments selecting outside counsel.',
    maxTokens: 6000,
    temperature: 0.5,
    wave: 3,
  },
  {
    name: 'Legal Department Org Design Advisor',
    slug: 'legal-department-org-design-advisor',
    description: 'Propose an organizational design for an in-house legal department based on size and strategy.',
    category: 'analytics',
    inputType: 'text',
    outputType: 'document',
    pricingTier: 'enterprise',
    promptTemplate: `You are a management consultant for in-house legal departments. Based on the company profile and goals below, propose an org design for the legal function.\n\nCompany and legal dept context:\n{{input}}\n\nProvide:\n1. Recommended org structure (teams and reporting lines)\n2. Key roles and headcount by level\n3. Centralization vs. embedded model\n4. Suggested KPIs for the function\n5. 12–24 month hiring roadmap.`,
    systemPrompt: 'You are an expert in designing in-house legal department structures and operating models.',
    maxTokens: 5500,
    temperature: 0.6,
    wave: 3,
  },
]
