/**
 * Wave 3 Compliance & Regulatory Tools (25 tools)
 */

export const WAVE3_COMPLIANCE_TOOLS = [
  {
    name: 'AML Compliance Checker',
    slug: 'aml-compliance-checker',
    description: 'Check anti-money laundering compliance',
    category: 'compliance',
    inputType: 'structured',
    outputType: 'text',
    pricingTier: 'enterprise',
    promptTemplate: 'Check AML compliance:\n\n{{input}}\n\nAnalyze BSA/AML requirements and risks.',
    systemPrompt: 'You are an AML compliance expert.',
    maxTokens: 4000,
    temperature: 0.4,
    wave: 3,
  },
  {
    name: 'KYC Documentation Generator',
    slug: 'kyc-documentation-generator',
    description: 'Generate KYC documentation and checklists',
    category: 'compliance',
    inputType: 'structured',
    outputType: 'document',
    pricingTier: 'professional',
    promptTemplate: 'Generate KYC documentation:\n\n{{input}}\n\nCreate customer due diligence checklist.',
    systemPrompt: 'You are a KYC compliance expert.',
    maxTokens: 3000,
    temperature: 0.4,
    wave: 3,
  },
  {
    name: 'OFAC Sanctions Screener',
    slug: 'ofac-sanctions-screener',
    description: 'Screen parties against OFAC sanctions lists',
    category: 'compliance',
    inputType: 'structured',
    outputType: 'json',
    pricingTier: 'enterprise',
    promptTemplate: 'Screen for OFAC sanctions:\n\n{{input}}\n\nProvide screening results and risk analysis.',
    systemPrompt: 'You are a sanctions compliance expert.',
    maxTokens: 3000,
    temperature: 0.3,
    wave: 3,
  },
  {
    name: 'Export Control Classifier',
    slug: 'export-control-classifier',
    description: 'Classify items under export control regulations',
    category: 'compliance',
    inputType: 'text',
    outputType: 'json',
    pricingTier: 'enterprise',
    promptTemplate: 'Classify for export control:\n\n{{input}}\n\nProvide ECCN and licensing requirements.',
    systemPrompt: 'You are an export control expert.',
    maxTokens: 4000,
    temperature: 0.4,
    wave: 3,
  },
  {
    name: 'FDA Regulatory Advisor',
    slug: 'fda-regulatory-advisor',
    description: 'Advise on FDA regulatory requirements',
    category: 'compliance',
    inputType: 'text',
    outputType: 'text',
    pricingTier: 'enterprise',
    promptTemplate: 'Advise on FDA requirements:\n\n{{input}}\n\nProvide regulatory pathway and requirements.',
    systemPrompt: 'You are an FDA regulatory expert.',
    maxTokens: 5000,
    temperature: 0.5,
    wave: 3,
  },
  {
    name: 'SEC Filing Analyzer',
    slug: 'sec-filing-analyzer',
    description: 'Analyze SEC filings and disclosure requirements',
    category: 'corporate-law',
    inputType: 'document',
    outputType: 'text',
    pricingTier: 'enterprise',
    promptTemplate: 'Analyze SEC filing:\n\n{{input}}\n\nReview disclosure adequacy and compliance.',
    systemPrompt: 'You are a securities law expert.',
    maxTokens: 5000,
    temperature: 0.5,
    wave: 3,
  },
  {
    name: 'Proxy Statement Drafter',
    slug: 'proxy-statement-drafter',
    description: 'Draft proxy statements and shareholder communications',
    category: 'corporate-law',
    inputType: 'structured',
    outputType: 'document',
    pricingTier: 'enterprise',
    promptTemplate: 'Draft proxy statement:\n\n{{input}}\n\nCreate SEC-compliant proxy materials.',
    systemPrompt: 'You are a securities disclosure expert.',
    maxTokens: 8000,
    temperature: 0.4,
    wave: 3,
  },
  {
    name: 'Insider Trading Policy Drafter',
    slug: 'insider-trading-policy-drafter',
    description: 'Draft insider trading policies and procedures',
    category: 'compliance',
    inputType: 'structured',
    outputType: 'document',
    pricingTier: 'professional',
    promptTemplate: 'Draft insider trading policy:\n\n{{input}}\n\nCreate comprehensive trading policy.',
    systemPrompt: 'You are a securities compliance expert.',
    maxTokens: 5000,
    temperature: 0.4,
    wave: 3,
  },
  {
    name: 'Code of Conduct Drafter',
    slug: 'code-of-conduct-drafter',
    description: 'Draft corporate codes of conduct',
    category: 'compliance',
    inputType: 'structured',
    outputType: 'document',
    pricingTier: 'professional',
    promptTemplate: 'Draft code of conduct:\n\n{{input}}\n\nCreate comprehensive ethics code.',
    systemPrompt: 'You are a corporate compliance expert.',
    maxTokens: 6000,
    temperature: 0.5,
    wave: 3,
  },
  {
    name: 'Conflict of Interest Policy Drafter',
    slug: 'conflict-of-interest-policy-drafter',
    description: 'Draft conflict of interest policies',
    category: 'compliance',
    inputType: 'structured',
    outputType: 'document',
    pricingTier: 'professional',
    promptTemplate: 'Draft COI policy:\n\n{{input}}\n\nCreate conflict management procedures.',
    systemPrompt: 'You are a corporate governance expert.',
    maxTokens: 4000,
    temperature: 0.4,
    wave: 3,
  },
  {
    name: 'Related Party Transaction Analyzer',
    slug: 'related-party-transaction-analyzer',
    description: 'Analyze related party transactions for compliance',
    category: 'corporate-law',
    inputType: 'structured',
    outputType: 'text',
    pricingTier: 'professional',
    promptTemplate: 'Analyze related party transaction:\n\n{{input}}\n\nProvide disclosure and approval requirements.',
    systemPrompt: 'You are a corporate governance expert.',
    maxTokens: 4000,
    temperature: 0.5,
    wave: 3,
  },
  {
    name: 'Board Committee Charter Drafter',
    slug: 'board-committee-charter-drafter',
    description: 'Draft board committee charters',
    category: 'corporate-law',
    inputType: 'structured',
    outputType: 'document',
    pricingTier: 'professional',
    promptTemplate: 'Draft committee charter:\n\n{{input}}\n\nCreate comprehensive committee charter.',
    systemPrompt: 'You are a corporate governance expert.',
    maxTokens: 4000,
    temperature: 0.4,
    wave: 3,
  },
  {
    name: 'D&O Questionnaire Generator',
    slug: 'do-questionnaire-generator',
    description: 'Generate D&O questionnaires for SEC filings',
    category: 'corporate-law',
    inputType: 'structured',
    outputType: 'document',
    pricingTier: 'professional',
    promptTemplate: 'Generate D&O questionnaire:\n\n{{input}}\n\nCreate comprehensive disclosure questionnaire.',
    systemPrompt: 'You are a securities disclosure expert.',
    maxTokens: 5000,
    temperature: 0.4,
    wave: 3,
  },
  {
    name: 'Beneficial Ownership Analyzer',
    slug: 'beneficial-ownership-analyzer',
    description: 'Analyze beneficial ownership reporting requirements',
    category: 'compliance',
    inputType: 'structured',
    outputType: 'text',
    pricingTier: 'professional',
    promptTemplate: 'Analyze beneficial ownership:\n\n{{input}}\n\nProvide reporting requirements and deadlines.',
    systemPrompt: 'You are a corporate transparency expert.',
    maxTokens: 3000,
    temperature: 0.4,
    wave: 3,
  },
  {
    name: 'Lobbying Disclosure Advisor',
    slug: 'lobbying-disclosure-advisor',
    description: 'Advise on lobbying disclosure requirements',
    category: 'compliance',
    inputType: 'text',
    outputType: 'text',
    pricingTier: 'professional',
    promptTemplate: 'Advise on lobbying disclosure:\n\n{{input}}\n\nProvide LDA and state requirements.',
    systemPrompt: 'You are a government affairs compliance expert.',
    maxTokens: 4000,
    temperature: 0.5,
    wave: 3,
  },
  {
    name: 'Political Contribution Compliance',
    slug: 'political-contribution-compliance',
    description: 'Check political contribution compliance',
    category: 'compliance',
    inputType: 'structured',
    outputType: 'text',
    pricingTier: 'professional',
    promptTemplate: 'Check political contribution compliance:\n\n{{input}}\n\nAnalyze pay-to-play and contribution limits.',
    systemPrompt: 'You are a political law compliance expert.',
    maxTokens: 4000,
    temperature: 0.4,
    wave: 3,
  },
  {
    name: 'Nonprofit Compliance Checker',
    slug: 'nonprofit-compliance-checker',
    description: 'Check nonprofit tax and governance compliance',
    category: 'compliance',
    inputType: 'structured',
    outputType: 'text',
    pricingTier: 'professional',
    promptTemplate: 'Check nonprofit compliance:\n\n{{input}}\n\nAnalyze 501(c)(3) requirements and governance.',
    systemPrompt: 'You are a nonprofit law expert.',
    maxTokens: 4000,
    temperature: 0.5,
    wave: 3,
  },
  {
    name: 'Form 990 Analyzer',
    slug: 'form-990-analyzer',
    description: 'Analyze Form 990 filings for nonprofits',
    category: 'tax-law',
    inputType: 'document',
    outputType: 'text',
    pricingTier: 'professional',
    promptTemplate: 'Analyze Form 990:\n\n{{input}}\n\nReview disclosure and compliance issues.',
    systemPrompt: 'You are a nonprofit tax expert.',
    maxTokens: 4000,
    temperature: 0.5,
    wave: 3,
  },
  {
    name: 'Grant Agreement Analyzer',
    slug: 'grant-agreement-analyzer',
    description: 'Analyze grant agreements and compliance requirements',
    category: 'contract-review',
    inputType: 'document',
    outputType: 'text',
    pricingTier: 'professional',
    promptTemplate: 'Analyze grant agreement:\n\n{{input}}\n\nReview terms and compliance obligations.',
    systemPrompt: 'You are a grants management expert.',
    maxTokens: 4000,
    temperature: 0.5,
    wave: 3,
  },
  {
    name: 'Government Contract Compliance',
    slug: 'government-contract-compliance',
    description: 'Check government contract compliance requirements',
    category: 'compliance',
    inputType: 'document',
    outputType: 'text',
    pricingTier: 'enterprise',
    promptTemplate: 'Check government contract compliance:\n\n{{input}}\n\nAnalyze FAR and agency requirements.',
    systemPrompt: 'You are a government contracts expert.',
    maxTokens: 5000,
    temperature: 0.5,
    wave: 3,
  },
  {
    name: 'SBIR/STTR Proposal Advisor',
    slug: 'sbir-sttr-proposal-advisor',
    description: 'Advise on SBIR/STTR proposal requirements',
    category: 'compliance',
    inputType: 'text',
    outputType: 'text',
    pricingTier: 'professional',
    promptTemplate: 'Advise on SBIR/STTR:\n\n{{input}}\n\nProvide eligibility and proposal guidance.',
    systemPrompt: 'You are a government grants expert.',
    maxTokens: 4000,
    temperature: 0.5,
    wave: 3,
  },
  {
    name: 'Accessibility Compliance Audit',
    slug: 'accessibility-compliance-audit',
    description: 'Audit digital accessibility compliance',
    category: 'compliance',
    inputType: 'text',
    outputType: 'text',
    pricingTier: 'professional',
    promptTemplate: 'Audit accessibility compliance:\n\n{{input}}\n\nAnalyze WCAG and ADA requirements.',
    systemPrompt: 'You are a digital accessibility expert.',
    maxTokens: 4000,
    temperature: 0.5,
    wave: 3,
  },
  {
    name: 'Consumer Protection Compliance',
    slug: 'consumer-protection-compliance',
    description: 'Check consumer protection law compliance',
    category: 'compliance',
    inputType: 'text',
    outputType: 'text',
    pricingTier: 'professional',
    promptTemplate: 'Check consumer protection compliance:\n\n{{input}}\n\nAnalyze FTC Act and state requirements.',
    systemPrompt: 'You are a consumer protection law expert.',
    maxTokens: 4000,
    temperature: 0.5,
    wave: 3,
  },
  {
    name: 'Advertising Compliance Reviewer',
    slug: 'advertising-compliance-reviewer',
    description: 'Review advertising for legal compliance',
    category: 'compliance',
    inputType: 'text',
    outputType: 'text',
    pricingTier: 'professional',
    promptTemplate: 'Review advertising compliance:\n\n{{input}}\n\nAnalyze FTC, NAD, and industry requirements.',
    systemPrompt: 'You are an advertising law expert.',
    maxTokens: 4000,
    temperature: 0.5,
    wave: 3,
  },
  {
    name: 'Product Liability Risk Assessor',
    slug: 'product-liability-risk-assessor',
    description: 'Assess product liability risks and warnings',
    category: 'compliance',
    inputType: 'text',
    outputType: 'text',
    pricingTier: 'professional',
    promptTemplate: 'Assess product liability risk:\n\n{{input}}\n\nAnalyze design, warning, and manufacturing risks.',
    systemPrompt: 'You are a product liability expert.',
    maxTokens: 4000,
    temperature: 0.5,
    wave: 3,
  },
]
