/**
 * Wave 2 Additional Real Estate & Construction Tools (10 tools)
 */

export const WAVE2_REALESTATE_TOOLS = [
  {
    name: 'Construction Contract Analyzer',
    slug: 'construction-contract-analyzer',
    description: 'Analyze construction contracts for risks and compliance',
    category: 'contract-review',
    inputType: 'document',
    outputType: 'text',
    pricingTier: 'professional',
    promptTemplate: 'Analyze construction contract:\n\n{{input}}\n\nReview scope, payment, change orders, delays, and disputes.',
    systemPrompt: 'You are a construction law expert.',
    maxTokens: 5000,
    temperature: 0.5,
    wave: 2,
  },
  {
    name: 'Mechanics Lien Drafter',
    slug: 'mechanics-lien-drafter',
    description: 'Draft mechanics lien notices and claims',
    category: 'real-estate',
    inputType: 'structured',
    outputType: 'document',
    pricingTier: 'professional',
    promptTemplate: 'Draft mechanics lien:\n\n{{input}}\n\nInclude property, claimant, amount, and statutory requirements.',
    systemPrompt: 'You are a construction law expert on mechanics liens.',
    maxTokens: 4000,
    temperature: 0.4,
    wave: 2,
  },
  {
    name: 'Zoning Analysis Tool',
    slug: 'zoning-analysis-tool',
    description: 'Analyze zoning regulations and permitted uses',
    category: 'real-estate',
    inputType: 'text',
    outputType: 'text',
    pricingTier: 'professional',
    promptTemplate: 'Analyze zoning:\n\n{{input}}\n\nProvide classification, permitted uses, and variance requirements.',
    systemPrompt: 'You are a land use and zoning law expert.',
    maxTokens: 4000,
    temperature: 0.5,
    wave: 2,
  },
  {
    name: 'Easement Drafter',
    slug: 'easement-drafter',
    description: 'Draft easement agreements for real property',
    category: 'real-estate',
    inputType: 'structured',
    outputType: 'document',
    pricingTier: 'professional',
    promptTemplate: 'Draft easement:\n\n{{input}}\n\nInclude purpose, scope, maintenance, and recording provisions.',
    systemPrompt: 'You are a real estate attorney on property rights.',
    maxTokens: 4000,
    temperature: 0.4,
    wave: 2,
  },
  {
    name: 'HOA Document Analyzer',
    slug: 'hoa-document-analyzer',
    description: 'Analyze HOA governing documents and CC&Rs',
    category: 'real-estate',
    inputType: 'document',
    outputType: 'text',
    pricingTier: 'pro',
    promptTemplate: 'Analyze HOA documents:\n\n{{input}}\n\nReview restrictions, assessments, and enforcement.',
    systemPrompt: 'You are a real estate attorney on community associations.',
    maxTokens: 4000,
    temperature: 0.5,
    wave: 2,
  },
  {
    name: 'Title Insurance Review',
    slug: 'title-insurance-review',
    description: 'Review title commitments and insurance policies',
    category: 'real-estate',
    inputType: 'document',
    outputType: 'text',
    pricingTier: 'professional',
    promptTemplate: 'Review title commitment:\n\n{{input}}\n\nAnalyze exceptions, requirements, and coverage issues.',
    systemPrompt: 'You are a real estate attorney specializing in title matters.',
    maxTokens: 4000,
    temperature: 0.5,
    wave: 2,
  },
  {
    name: 'Property Tax Appeal Drafter',
    slug: 'property-tax-appeal-drafter',
    description: 'Draft property tax assessment appeals',
    category: 'tax-law',
    inputType: 'structured',
    outputType: 'document',
    pricingTier: 'professional',
    promptTemplate: 'Draft property tax appeal:\n\n{{input}}\n\nInclude valuation arguments and comparable sales.',
    systemPrompt: 'You are a property tax attorney.',
    maxTokens: 4000,
    temperature: 0.5,
    wave: 2,
  },
  {
    name: 'Eminent Domain Analyzer',
    slug: 'eminent-domain-analyzer',
    description: 'Analyze eminent domain and condemnation issues',
    category: 'real-estate',
    inputType: 'text',
    outputType: 'text',
    pricingTier: 'professional',
    promptTemplate: 'Analyze eminent domain:\n\n{{input}}\n\nProvide just compensation and procedural analysis.',
    systemPrompt: 'You are an eminent domain law expert.',
    maxTokens: 4000,
    temperature: 0.5,
    wave: 2,
  },
  {
    name: 'ADA Accessibility Compliance',
    slug: 'ada-accessibility-compliance',
    description: 'Analyze ADA accessibility compliance for properties',
    category: 'compliance',
    inputType: 'text',
    outputType: 'text',
    pricingTier: 'professional',
    promptTemplate: 'Analyze ADA compliance:\n\n{{input}}\n\nProvide accessibility requirements and remediation.',
    systemPrompt: 'You are an ADA compliance expert.',
    maxTokens: 4000,
    temperature: 0.5,
    wave: 2,
  },
  {
    name: 'Landlord-Tenant Dispute Advisor',
    slug: 'landlord-tenant-dispute-advisor',
    description: 'Advise on landlord-tenant disputes and evictions',
    category: 'real-estate',
    inputType: 'text',
    outputType: 'text',
    pricingTier: 'pro',
    promptTemplate: 'Analyze landlord-tenant dispute:\n\n{{input}}\n\nProvide rights, remedies, and eviction procedures.',
    systemPrompt: 'You are a landlord-tenant law expert.',
    maxTokens: 4000,
    temperature: 0.5,
    wave: 2,
  },
]
