/**
 * Wave 3: Analytics, Billing & Client Management Tools (20 tools)
 */
export const WAVE3_ANALYTICS_TOOLS = [
  {
    name: 'Judge Analytics Report',
    slug: 'judge-analytics-report',
    description: 'Analyze judge tendencies and ruling patterns',
    category: 'analytics',
    inputType: 'text',
    outputType: 'text',
    pricingTier: 'professional',
    promptTemplate: `Analyze judge tendencies for:\n\n{{input}}\n\nProvide: Background, ruling patterns, trial preferences, key opinions, strategic recommendations.`,
    systemPrompt: 'You are a litigation analytics expert.',
    maxTokens: 4000,
    temperature: 0.5,
    wave: 3,
  },
  {
    name: 'Case Outcome Predictor',
    slug: 'case-outcome-predictor',
    description: 'Predict case outcomes based on factors and precedents',
    category: 'analytics',
    inputType: 'structured',
    outputType: 'json',
    pricingTier: 'enterprise',
    promptTemplate: `Predict outcome for:\n\n{{input}}\n\nAnalyze: Key factors, comparable cases, outcome probability, damages range, timeline estimate.`,
    systemPrompt: 'You are a legal analytics expert predicting case outcomes.',
    maxTokens: 3000,
    temperature: 0.5,
    wave: 3,
  },
  {
    name: 'Time Entry Optimizer',
    slug: 'time-entry-optimizer',
    description: 'Optimize time entries for billing compliance',
    category: 'billing',
    inputType: 'text',
    outputType: 'text',
    pricingTier: 'pro',
    promptTemplate: `Optimize these time entries:\n\n{{input}}\n\nImprove: Description clarity, block billing issues, vague entries, compliance issues.`,
    systemPrompt: 'You are a legal billing expert.',
    maxTokens: 3000,
    temperature: 0.4,
    wave: 3,
  },
  {
    name: 'Budget Estimator',
    slug: 'budget-estimator',
    description: 'Estimate legal matter budgets',
    category: 'billing',
    inputType: 'structured',
    outputType: 'json',
    pricingTier: 'professional',
    promptTemplate: `Estimate budget for:\n\n{{input}}\n\nProvide: Phase breakdown, task estimates, staffing model, total estimate range.`,
    systemPrompt: 'You are a legal project manager estimating budgets.',
    maxTokens: 4000,
    temperature: 0.5,
    wave: 3,
  },
  {
    name: 'Client Intake Form Generator',
    slug: 'client-intake-form-generator',
    description: 'Generate customized client intake forms',
    category: 'client-management',
    inputType: 'structured',
    outputType: 'document',
    pricingTier: 'pro',
    promptTemplate: `Generate intake form for:\n\n{{input}}\n\nInclude: Contact info, matter info, conflict check, fee agreement, document checklist.`,
    systemPrompt: 'You are a law firm administrator creating intake forms.',
    maxTokens: 4000,
    temperature: 0.4,
    wave: 3,
  },
  {
    name: 'Engagement Letter Drafter',
    slug: 'engagement-letter-drafter',
    description: 'Draft client engagement and retainer letters',
    category: 'client-management',
    inputType: 'structured',
    outputType: 'document',
    pricingTier: 'pro',
    promptTemplate: `Draft engagement letter for:\n\n{{input}}\n\nInclude: Scope, fee arrangement, retainer, billing practices, termination.`,
    systemPrompt: 'You are a law firm attorney drafting engagement letters.',
    maxTokens: 4000,
    temperature: 0.4,
    wave: 3,
  },
  {
    name: 'Conflict Check Assistant',
    slug: 'conflict-check-assistant',
    description: 'Assist with conflict of interest checks',
    category: 'client-management',
    inputType: 'structured',
    outputType: 'text',
    pricingTier: 'pro',
    promptTemplate: `Check conflicts for:\n\n{{input}}\n\nAnalyze: Direct, indirect, business, former client, imputed conflicts.`,
    systemPrompt: 'You are a conflicts attorney analyzing potential conflicts.',
    maxTokens: 3000,
    temperature: 0.4,
    wave: 3,
  },
  {
    name: 'Matter Status Report Generator',
    slug: 'matter-status-report-generator',
    description: 'Generate matter status reports for clients',
    category: 'client-management',
    inputType: 'structured',
    outputType: 'document',
    pricingTier: 'pro',
    promptTemplate: `Generate status report for:\n\n{{input}}\n\nInclude: Executive summary, recent activity, upcoming events, budget status.`,
    systemPrompt: 'You are a legal project manager creating status reports.',
    maxTokens: 3000,
    temperature: 0.4,
    wave: 3,
  },
  {
    name: 'Precedent Document Finder',
    slug: 'precedent-document-finder',
    description: 'Find relevant precedent documents from firm library',
    category: 'knowledge-management',
    inputType: 'text',
    outputType: 'text',
    pricingTier: 'pro',
    promptTemplate: `Find precedent documents for:\n\n{{input}}\n\nRecommend: Document type, search terms, similar matters, key provisions.`,
    systemPrompt: 'You are a knowledge management specialist.',
    maxTokens: 3000,
    temperature: 0.5,
    wave: 3,
  },
  {
    name: 'Workflow Automation Designer',
    slug: 'workflow-automation-designer',
    description: 'Design legal workflow automations',
    category: 'collaborative',
    inputType: 'text',
    outputType: 'document',
    pricingTier: 'professional',
    promptTemplate: `Design workflow for:\n\n{{input}}\n\nCreate: Process map, triggers, tasks, assignments, deadlines, notifications.`,
    systemPrompt: 'You are a legal operations expert designing workflows.',
    maxTokens: 4000,
    temperature: 0.5,
    wave: 3,
  },
  {
    name: 'Deadline Calculator',
    slug: 'deadline-calculator',
    description: 'Calculate legal deadlines and court dates',
    category: 'collaborative',
    inputType: 'structured',
    outputType: 'json',
    pricingTier: 'pro',
    promptTemplate: `Calculate deadlines for:\n\n{{input}}\n\nProvide: Trigger date, applicable rules, calculated deadlines, adjustments.`,
    systemPrompt: 'You are a legal calendar specialist calculating deadlines.',
    maxTokens: 2000,
    temperature: 0.3,
    wave: 3,
  },
  {
    name: 'Risk Assessment Matrix',
    slug: 'risk-assessment-matrix',
    description: 'Create legal risk assessment matrices',
    category: 'analytics',
    inputType: 'text',
    outputType: 'document',
    pricingTier: 'professional',
    promptTemplate: `Create risk assessment for:\n\n{{input}}\n\nAnalyze: Risk identification, likelihood, impact, mitigation strategies.`,
    systemPrompt: 'You are a legal risk management expert.',
    maxTokens: 4000,
    temperature: 0.5,
    wave: 3,
  },
  {
    name: 'Compliance Calendar Generator',
    slug: 'compliance-calendar-generator',
    description: 'Generate compliance deadline calendars',
    category: 'compliance',
    inputType: 'structured',
    outputType: 'document',
    pricingTier: 'professional',
    promptTemplate: `Generate compliance calendar for:\n\n{{input}}\n\nInclude: Regulatory deadlines, reporting requirements, renewal dates.`,
    systemPrompt: 'You are a compliance officer creating calendars.',
    maxTokens: 4000,
    temperature: 0.4,
    wave: 3,
  },
  {
    name: 'Policy Gap Analyzer',
    slug: 'policy-gap-analyzer',
    description: 'Analyze corporate policies for gaps',
    category: 'compliance',
    inputType: 'document',
    outputType: 'text',
    pricingTier: 'professional',
    promptTemplate: `Analyze policies for gaps:\n\n{{input}}\n\nEvaluate: Coverage, missing policies, outdated provisions, recommendations.`,
    systemPrompt: 'You are a compliance consultant reviewing policies.',
    maxTokens: 4000,
    temperature: 0.5,
    wave: 3,
  },
  {
    name: 'Divorce Settlement Calculator',
    slug: 'divorce-settlement-calculator',
    description: 'Calculate equitable distribution and support obligations',
    category: 'family-law',
    inputType: 'structured',
    outputType: 'json',
    pricingTier: 'professional',
    promptTemplate: `Calculate divorce settlement:\n\n{{input}}\n\nAnalyze: Asset division, alimony factors, child support, tax implications.`,
    systemPrompt: 'You are a family law financial expert.',
    maxTokens: 4000,
    temperature: 0.4,
    wave: 3,
  },
  {
    name: 'Will Drafter Pro',
    slug: 'will-drafter-pro',
    description: 'Draft comprehensive last will and testament documents',
    category: 'specialized-areas',
    inputType: 'structured',
    outputType: 'document',
    pricingTier: 'pro',
    promptTemplate: `Draft a will:\n\n{{input}}\n\nInclude: Declarations, debts, specific bequests, residuary estate, executor, guardians.`,
    systemPrompt: 'You are an estate planning attorney.',
    maxTokens: 5000,
    temperature: 0.4,
    wave: 3,
  },
  {
    name: 'Power of Attorney Generator',
    slug: 'power-of-attorney-generator',
    description: 'Generate durable and healthcare powers of attorney',
    category: 'specialized-areas',
    inputType: 'structured',
    outputType: 'document',
    pricingTier: 'pro',
    promptTemplate: `Generate power of attorney:\n\n{{input}}\n\nInclude: Principal, agent, powers granted, limitations, durability, effective date.`,
    systemPrompt: 'You are an estate planning attorney.',
    maxTokens: 4000,
    temperature: 0.4,
    wave: 3,
  },
  {
    name: 'Healthcare Directive Drafter',
    slug: 'healthcare-directive-drafter',
    description: 'Draft advance healthcare directives and living wills',
    category: 'specialized-areas',
    inputType: 'structured',
    outputType: 'document',
    pricingTier: 'pro',
    promptTemplate: `Draft healthcare directive:\n\n{{input}}\n\nInclude: Healthcare agent, treatment preferences, end-of-life wishes, organ donation.`,
    systemPrompt: 'You are an estate planning attorney.',
    maxTokens: 4000,
    temperature: 0.4,
    wave: 3,
  },
  {
    name: 'International Trade Analyzer',
    slug: 'international-trade-analyzer',
    description: 'Analyze international trade compliance issues',
    category: 'international',
    inputType: 'text',
    outputType: 'text',
    pricingTier: 'enterprise',
    promptTemplate: `Analyze trade compliance:\n\n{{input}}\n\nEvaluate: Export controls, sanctions, tariffs, customs, compliance requirements.`,
    systemPrompt: 'You are an international trade attorney.',
    maxTokens: 4000,
    temperature: 0.5,
    wave: 3,
  },
  {
    name: 'Cross-Border Transaction Advisor',
    slug: 'cross-border-transaction-advisor',
    description: 'Advise on cross-border transaction structuring',
    category: 'international',
    inputType: 'structured',
    outputType: 'text',
    pricingTier: 'enterprise',
    promptTemplate: `Advise on cross-border transaction:\n\n{{input}}\n\nAddress: Structure options, tax implications, regulatory approvals, risk factors.`,
    systemPrompt: 'You are an international transactions attorney.',
    maxTokens: 5000,
    temperature: 0.5,
    wave: 3,
  },
]
