/**
 * Wave 2 Additional Employment Tools (10 tools)
 */

export const WAVE2_EMPLOYMENT_TOOLS = [
  {
    name: 'Labor Union Negotiation Advisor',
    slug: 'labor-union-negotiation-advisor',
    description: 'Advise on collective bargaining and union negotiations',
    category: 'employment-law',
    inputType: 'text',
    outputType: 'text',
    pricingTier: 'professional',
    promptTemplate: 'Analyze labor negotiation:\n\n{{input}}\n\nProvide bargaining issues, NLRA compliance, strategies, and recommendations.',
    systemPrompt: 'You are a labor law expert specializing in union negotiations.',
    maxTokens: 4000,
    temperature: 0.6,
    wave: 2,
  },
  {
    name: 'FMLA Leave Analyzer',
    slug: 'fmla-leave-analyzer',
    description: 'Analyze FMLA eligibility and leave calculations',
    category: 'employment-law',
    inputType: 'structured',
    outputType: 'json',
    pricingTier: 'pro',
    promptTemplate: 'Analyze FMLA eligibility:\n\n{{input}}\n\nProvide eligibility, entitlement, and documentation requirements.',
    systemPrompt: 'You are an employment law expert specializing in FMLA.',
    maxTokens: 3000,
    temperature: 0.4,
    wave: 2,
  },
  {
    name: 'Wage and Hour Compliance Checker',
    slug: 'wage-hour-compliance-checker',
    description: 'Check FLSA and state wage law compliance',
    category: 'employment-law',
    inputType: 'structured',
    outputType: 'text',
    pricingTier: 'professional',
    promptTemplate: 'Analyze wage compliance:\n\n{{input}}\n\nCheck minimum wage, overtime, exemptions, and recordkeeping.',
    systemPrompt: 'You are a wage and hour law expert.',
    maxTokens: 4000,
    temperature: 0.4,
    wave: 2,
  },
  {
    name: 'Non-Compete Enforceability Analyzer',
    slug: 'non-compete-enforceability-analyzer',
    description: 'Analyze non-compete agreement enforceability',
    category: 'employment-law',
    inputType: 'document',
    outputType: 'text',
    pricingTier: 'professional',
    promptTemplate: 'Analyze non-compete:\n\n{{input}}\n\nProvide enforceability analysis by jurisdiction.',
    systemPrompt: 'You are an employment law expert on restrictive covenants.',
    maxTokens: 4000,
    temperature: 0.5,
    wave: 2,
  },
  {
    name: 'ERISA Benefits Analyzer',
    slug: 'erisa-benefits-analyzer',
    description: 'Analyze employee benefit plans for ERISA compliance',
    category: 'employment-law',
    inputType: 'document',
    outputType: 'text',
    pricingTier: 'enterprise',
    promptTemplate: 'Analyze ERISA compliance:\n\n{{input}}\n\nReview plan documents, fiduciary duties, and disclosures.',
    systemPrompt: 'You are an ERISA compliance expert.',
    maxTokens: 5000,
    temperature: 0.4,
    wave: 2,
  },
  {
    name: 'Title IX Compliance Advisor',
    slug: 'title-ix-compliance-advisor',
    description: 'Advise on Title IX compliance for educational institutions',
    category: 'compliance',
    inputType: 'text',
    outputType: 'text',
    pricingTier: 'professional',
    promptTemplate: 'Analyze Title IX compliance:\n\n{{input}}\n\nProvide policy and investigation requirements.',
    systemPrompt: 'You are a Title IX compliance expert.',
    maxTokens: 4000,
    temperature: 0.5,
    wave: 2,
  },
  {
    name: 'Severance Agreement Drafter',
    slug: 'severance-agreement-drafter',
    description: 'Draft employee severance and separation agreements',
    category: 'employment-law',
    inputType: 'structured',
    outputType: 'document',
    pricingTier: 'professional',
    promptTemplate: 'Draft severance agreement:\n\n{{input}}\n\nInclude release, consideration, OWBPA compliance.',
    systemPrompt: 'You are an employment attorney drafting separation agreements.',
    maxTokens: 4000,
    temperature: 0.4,
    wave: 2,
  },
  {
    name: 'I-9 Compliance Checker',
    slug: 'i9-compliance-checker',
    description: 'Check I-9 employment verification compliance',
    category: 'immigration',
    inputType: 'structured',
    outputType: 'text',
    pricingTier: 'pro',
    promptTemplate: 'Check I-9 compliance:\n\n{{input}}\n\nReview documentation and timing requirements.',
    systemPrompt: 'You are an immigration compliance expert.',
    maxTokens: 3000,
    temperature: 0.4,
    wave: 2,
  },
  {
    name: 'OSHA Compliance Advisor',
    slug: 'osha-compliance-advisor',
    description: 'Advise on OSHA workplace safety compliance',
    category: 'compliance',
    inputType: 'text',
    outputType: 'text',
    pricingTier: 'professional',
    promptTemplate: 'Analyze OSHA compliance:\n\n{{input}}\n\nProvide safety requirements and violation risks.',
    systemPrompt: 'You are an OSHA compliance expert.',
    maxTokens: 4000,
    temperature: 0.5,
    wave: 2,
  },
  {
    name: 'Workers Compensation Analyzer',
    slug: 'workers-compensation-analyzer',
    description: 'Analyze workers compensation claims and coverage',
    category: 'employment-law',
    inputType: 'text',
    outputType: 'text',
    pricingTier: 'professional',
    promptTemplate: 'Analyze workers comp claim:\n\n{{input}}\n\nProvide coverage analysis and benefit calculations.',
    systemPrompt: 'You are a workers compensation law expert.',
    maxTokens: 4000,
    temperature: 0.5,
    wave: 2,
  },
]
