/**
 * Wave 4: Advanced & Emerging Technology Tools (30 tools)
 */
export const WAVE4_ADVANCED_TOOLS = [
  {
    name: 'AI Ethics Advisor',
    slug: 'ai-ethics-advisor',
    description: 'Analyze AI systems for ethical and legal compliance',
    category: 'compliance',
    inputType: 'text',
    outputType: 'text',
    pricingTier: 'enterprise',
    promptTemplate: `Analyze AI ethics:\n\n{{input}}\n\nEvaluate: Bias risks, transparency, accountability, privacy, regulatory compliance, recommendations.`,
    systemPrompt: 'You are an AI ethics and law expert.',
    maxTokens: 4000,
    temperature: 0.5,
    wave: 4,
  },
  {
    name: 'Smart Contract Auditor',
    slug: 'smart-contract-auditor',
    description: 'Audit blockchain smart contracts for legal and security issues',
    category: 'compliance',
    inputType: 'text',
    outputType: 'text',
    pricingTier: 'enterprise',
    promptTemplate: `Audit this smart contract:\n\n{{input}}\n\nAnalyze: Legal enforceability, security vulnerabilities, regulatory issues, best practices.`,
    systemPrompt: 'You are a blockchain legal and security expert.',
    maxTokens: 5000,
    temperature: 0.4,
    wave: 4,
  },
  {
    name: 'Cryptocurrency Compliance Checker',
    slug: 'cryptocurrency-compliance-checker',
    description: 'Check cryptocurrency transactions for regulatory compliance',
    category: 'compliance',
    inputType: 'structured',
    outputType: 'text',
    pricingTier: 'enterprise',
    promptTemplate: `Check crypto compliance:\n\n{{input}}\n\nEvaluate: AML/KYC requirements, securities classification, tax reporting, sanctions screening.`,
    systemPrompt: 'You are a cryptocurrency regulatory expert.',
    maxTokens: 4000,
    temperature: 0.4,
    wave: 4,
  },
  {
    name: 'NFT Legal Analyzer',
    slug: 'nft-legal-analyzer',
    description: 'Analyze NFT projects for legal issues',
    category: 'intellectual-property',
    inputType: 'text',
    outputType: 'text',
    pricingTier: 'professional',
    promptTemplate: `Analyze NFT legal issues:\n\n{{input}}\n\nEvaluate: IP rights, securities issues, consumer protection, terms of sale, royalty structures.`,
    systemPrompt: 'You are an NFT and digital asset attorney.',
    maxTokens: 4000,
    temperature: 0.5,
    wave: 4,
  },
  {
    name: 'DAO Governance Advisor',
    slug: 'dao-governance-advisor',
    description: 'Advise on DAO legal structure and governance',
    category: 'corporate-law',
    inputType: 'text',
    outputType: 'text',
    pricingTier: 'enterprise',
    promptTemplate: `Advise on DAO governance:\n\n{{input}}\n\nAddress: Legal structure options, liability, voting mechanisms, regulatory compliance, best practices.`,
    systemPrompt: 'You are a DAO and blockchain governance expert.',
    maxTokens: 4000,
    temperature: 0.5,
    wave: 4,
  },
  {
    name: 'Metaverse Legal Advisor',
    slug: 'metaverse-legal-advisor',
    description: 'Advise on legal issues in virtual worlds and metaverse',
    category: 'intellectual-property',
    inputType: 'text',
    outputType: 'text',
    pricingTier: 'professional',
    promptTemplate: `Advise on metaverse legal issues:\n\n{{input}}\n\nAddress: Virtual property rights, IP protection, user agreements, content moderation, jurisdiction.`,
    systemPrompt: 'You are a metaverse and virtual worlds legal expert.',
    maxTokens: 4000,
    temperature: 0.5,
    wave: 4,
  },
  {
    name: 'Autonomous Vehicle Liability Analyzer',
    slug: 'autonomous-vehicle-liability-analyzer',
    description: 'Analyze liability issues for autonomous vehicles',
    category: 'specialized-areas',
    inputType: 'text',
    outputType: 'text',
    pricingTier: 'enterprise',
    promptTemplate: `Analyze AV liability:\n\n{{input}}\n\nEvaluate: Product liability, negligence, regulatory compliance, insurance, manufacturer vs operator liability.`,
    systemPrompt: 'You are an autonomous vehicle liability expert.',
    maxTokens: 4000,
    temperature: 0.5,
    wave: 4,
  },
  {
    name: 'Drone Regulations Advisor',
    slug: 'drone-regulations-advisor',
    description: 'Advise on drone operations and regulatory compliance',
    category: 'compliance',
    inputType: 'structured',
    outputType: 'text',
    pricingTier: 'professional',
    promptTemplate: `Advise on drone regulations:\n\n{{input}}\n\nAddress: FAA requirements, airspace restrictions, privacy issues, insurance, commercial operations.`,
    systemPrompt: 'You are a drone and aviation regulatory expert.',
    maxTokens: 3000,
    temperature: 0.4,
    wave: 4,
  },
  {
    name: 'Biometric Data Compliance',
    slug: 'biometric-data-compliance',
    description: 'Analyze biometric data collection for legal compliance',
    category: 'cybersecurity',
    inputType: 'text',
    outputType: 'text',
    pricingTier: 'professional',
    promptTemplate: `Analyze biometric compliance:\n\n{{input}}\n\nEvaluate: BIPA, consent requirements, data retention, security measures, employee vs customer data.`,
    systemPrompt: 'You are a biometric privacy law expert.',
    maxTokens: 4000,
    temperature: 0.4,
    wave: 4,
  },
  {
    name: 'Genetic Data Privacy Advisor',
    slug: 'genetic-data-privacy-advisor',
    description: 'Advise on genetic data privacy and GINA compliance',
    category: 'cybersecurity',
    inputType: 'text',
    outputType: 'text',
    pricingTier: 'enterprise',
    promptTemplate: `Advise on genetic data privacy:\n\n{{input}}\n\nAddress: GINA compliance, consent, research use, discrimination protections, data security.`,
    systemPrompt: 'You are a genetic privacy law expert.',
    maxTokens: 4000,
    temperature: 0.4,
    wave: 4,
  },
  {
    name: 'ESG Compliance Analyzer',
    slug: 'esg-compliance-analyzer',
    description: 'Analyze ESG disclosures and compliance',
    category: 'compliance',
    inputType: 'document',
    outputType: 'text',
    pricingTier: 'enterprise',
    promptTemplate: `Analyze ESG compliance:\n\n{{input}}\n\nEvaluate: Disclosure requirements, greenwashing risks, SEC rules, EU taxonomy, best practices.`,
    systemPrompt: 'You are an ESG and sustainability legal expert.',
    maxTokens: 5000,
    temperature: 0.5,
    wave: 4,
  },
  {
    name: 'Climate Litigation Risk Assessor',
    slug: 'climate-litigation-risk-assessor',
    description: 'Assess climate-related litigation risks',
    category: 'environmental',
    inputType: 'text',
    outputType: 'text',
    pricingTier: 'enterprise',
    promptTemplate: `Assess climate litigation risk:\n\n{{input}}\n\nEvaluate: Exposure areas, disclosure obligations, greenwashing claims, fiduciary duties, mitigation strategies.`,
    systemPrompt: 'You are a climate litigation expert.',
    maxTokens: 4000,
    temperature: 0.5,
    wave: 4,
  },
  {
    name: 'Supply Chain Due Diligence',
    slug: 'supply-chain-due-diligence',
    description: 'Conduct supply chain human rights due diligence',
    category: 'compliance',
    inputType: 'structured',
    outputType: 'document',
    pricingTier: 'enterprise',
    promptTemplate: `Conduct supply chain due diligence:\n\n{{input}}\n\nAnalyze: Forced labor risks, conflict minerals, child labor, environmental impact, remediation.`,
    systemPrompt: 'You are a supply chain compliance expert.',
    maxTokens: 5000,
    temperature: 0.5,
    wave: 4,
  },
  {
    name: 'Sanctions Screening Tool',
    slug: 'sanctions-screening-tool',
    description: 'Screen parties against sanctions lists',
    category: 'compliance',
    inputType: 'structured',
    outputType: 'json',
    pricingTier: 'professional',
    promptTemplate: `Screen for sanctions:\n\n{{input}}\n\nCheck: OFAC SDN, EU sanctions, UN sanctions, ownership analysis, risk assessment.`,
    systemPrompt: 'You are a sanctions compliance expert.',
    maxTokens: 3000,
    temperature: 0.3,
    wave: 4,
  },
  {
    name: 'Anti-Corruption Compliance',
    slug: 'anti-corruption-compliance',
    description: 'Analyze FCPA and anti-corruption compliance',
    category: 'compliance',
    inputType: 'text',
    outputType: 'text',
    pricingTier: 'professional',
    promptTemplate: `Analyze anti-corruption compliance:\n\n{{input}}\n\nEvaluate: FCPA risks, UK Bribery Act, third-party due diligence, gifts/hospitality, remediation.`,
    systemPrompt: 'You are an anti-corruption compliance expert.',
    maxTokens: 4000,
    temperature: 0.5,
    wave: 4,
  },
  {
    name: 'Whistleblower Policy Drafter',
    slug: 'whistleblower-policy-drafter',
    description: 'Draft whistleblower and ethics hotline policies',
    category: 'compliance',
    inputType: 'structured',
    outputType: 'document',
    pricingTier: 'professional',
    promptTemplate: `Draft whistleblower policy:\n\n{{input}}\n\nInclude: Reporting channels, anonymity protections, investigation process, non-retaliation, SEC requirements.`,
    systemPrompt: 'You are a compliance attorney drafting policies.',
    maxTokens: 4000,
    temperature: 0.4,
    wave: 4,
  },
  {
    name: 'Antitrust Risk Analyzer',
    slug: 'antitrust-risk-analyzer',
    description: 'Analyze antitrust and competition law risks',
    category: 'compliance',
    inputType: 'text',
    outputType: 'text',
    pricingTier: 'enterprise',
    promptTemplate: `Analyze antitrust risks:\n\n{{input}}\n\nEvaluate: Price fixing, market allocation, monopolization, vertical restraints, merger issues.`,
    systemPrompt: 'You are an antitrust attorney.',
    maxTokens: 4000,
    temperature: 0.5,
    wave: 4,
  },
  {
    name: 'Class Action Risk Assessor',
    slug: 'class-action-risk-assessor',
    description: 'Assess class action litigation exposure',
    category: 'litigation-support',
    inputType: 'text',
    outputType: 'text',
    pricingTier: 'enterprise',
    promptTemplate: `Assess class action risk:\n\n{{input}}\n\nEvaluate: Class certification factors, damages exposure, settlement value, defense strategies, insurance coverage.`,
    systemPrompt: 'You are a class action defense attorney.',
    maxTokens: 4000,
    temperature: 0.5,
    wave: 4,
  },
  {
    name: 'Mass Tort Analyzer',
    slug: 'mass-tort-analyzer',
    description: 'Analyze mass tort litigation exposure and strategy',
    category: 'litigation-support',
    inputType: 'text',
    outputType: 'text',
    pricingTier: 'enterprise',
    promptTemplate: `Analyze mass tort exposure:\n\n{{input}}\n\nEvaluate: Causation issues, bellwether strategy, MDL considerations, settlement structures, insurance.`,
    systemPrompt: 'You are a mass tort litigation expert.',
    maxTokens: 4000,
    temperature: 0.5,
    wave: 4,
  },
  {
    name: 'Insurance Coverage Analyzer',
    slug: 'insurance-coverage-analyzer',
    description: 'Analyze insurance coverage for claims',
    category: 'specialized-areas',
    inputType: 'document',
    outputType: 'text',
    pricingTier: 'professional',
    promptTemplate: `Analyze insurance coverage:\n\n{{input}}\n\nEvaluate: Policy terms, coverage triggers, exclusions, limits, notice requirements, bad faith issues.`,
    systemPrompt: 'You are an insurance coverage attorney.',
    maxTokens: 4000,
    temperature: 0.5,
    wave: 4,
  },
  {
    name: 'Arbitration Clause Drafter',
    slug: 'arbitration-clause-drafter',
    description: 'Draft arbitration clauses and ADR provisions',
    category: 'contract-review',
    inputType: 'structured',
    outputType: 'document',
    pricingTier: 'professional',
    promptTemplate: `Draft arbitration clause:\n\n{{input}}\n\nInclude: Arbitration rules, seat, language, arbitrator selection, class waiver, appeal rights.`,
    systemPrompt: 'You are an arbitration and ADR expert.',
    maxTokens: 3000,
    temperature: 0.4,
    wave: 4,
  },
  {
    name: 'International Arbitration Advisor',
    slug: 'international-arbitration-advisor',
    description: 'Advise on international arbitration strategy',
    category: 'international',
    inputType: 'text',
    outputType: 'text',
    pricingTier: 'enterprise',
    promptTemplate: `Advise on international arbitration:\n\n{{input}}\n\nAddress: Forum selection, applicable law, enforcement, interim measures, costs.`,
    systemPrompt: 'You are an international arbitration expert.',
    maxTokens: 4000,
    temperature: 0.5,
    wave: 4,
  },
  {
    name: 'Mediation Preparation Tool',
    slug: 'mediation-preparation-tool',
    description: 'Prepare for mediation sessions',
    category: 'litigation-support',
    inputType: 'text',
    outputType: 'document',
    pricingTier: 'professional',
    promptTemplate: `Prepare for mediation:\n\n{{input}}\n\nCreate: Position summary, BATNA analysis, opening statement, negotiation strategy, settlement authority.`,
    systemPrompt: 'You are a mediation preparation expert.',
    maxTokens: 4000,
    temperature: 0.5,
    wave: 4,
  },
  {
    name: 'Legal Tech Vendor Evaluator',
    slug: 'legal-tech-vendor-evaluator',
    description: 'Evaluate legal technology vendors and solutions',
    category: 'knowledge-management',
    inputType: 'structured',
    outputType: 'text',
    pricingTier: 'professional',
    promptTemplate: `Evaluate legal tech vendor:\n\n{{input}}\n\nAssess: Features, security, integration, pricing, support, implementation, ROI.`,
    systemPrompt: 'You are a legal technology consultant.',
    maxTokens: 4000,
    temperature: 0.5,
    wave: 4,
  },
  {
    name: 'Law Firm Merger Advisor',
    slug: 'law-firm-merger-advisor',
    description: 'Advise on law firm mergers and combinations',
    category: 'specialized-areas',
    inputType: 'text',
    outputType: 'text',
    pricingTier: 'enterprise',
    promptTemplate: `Advise on law firm merger:\n\n{{input}}\n\nAddress: Cultural fit, financial terms, governance, conflicts, client retention, integration.`,
    systemPrompt: 'You are a law firm management consultant.',
    maxTokens: 4000,
    temperature: 0.5,
    wave: 4,
  },
  {
    name: 'Legal Department Benchmarking',
    slug: 'legal-department-benchmarking',
    description: 'Benchmark legal department performance',
    category: 'analytics',
    inputType: 'structured',
    outputType: 'document',
    pricingTier: 'enterprise',
    promptTemplate: `Benchmark legal department:\n\n{{input}}\n\nAnalyze: Spend per revenue, staffing ratios, outside counsel mix, technology adoption, efficiency metrics.`,
    systemPrompt: 'You are a legal operations consultant.',
    maxTokens: 4000,
    temperature: 0.5,
    wave: 4,
  },
  {
    name: 'Alternative Fee Arrangement Designer',
    slug: 'alternative-fee-arrangement-designer',
    description: 'Design alternative fee arrangements',
    category: 'billing',
    inputType: 'structured',
    outputType: 'document',
    pricingTier: 'professional',
    promptTemplate: `Design AFA:\n\n{{input}}\n\nOptions: Fixed fee, capped fee, success fee, blended rate, portfolio pricing, risk sharing.`,
    systemPrompt: 'You are a legal pricing expert.',
    maxTokens: 3000,
    temperature: 0.5,
    wave: 4,
  },
  {
    name: 'Legal Project Management Plan',
    slug: 'legal-project-management-plan',
    description: 'Create legal project management plans',
    category: 'collaborative',
    inputType: 'structured',
    outputType: 'document',
    pricingTier: 'professional',
    promptTemplate: `Create LPM plan:\n\n{{input}}\n\nInclude: Scope, timeline, budget, resources, milestones, risks, communication plan.`,
    systemPrompt: 'You are a legal project manager.',
    maxTokens: 4000,
    temperature: 0.5,
    wave: 4,
  },
  {
    name: 'Diversity Metrics Analyzer',
    slug: 'diversity-metrics-analyzer',
    description: 'Analyze law firm diversity metrics and reporting',
    category: 'analytics',
    inputType: 'structured',
    outputType: 'document',
    pricingTier: 'professional',
    promptTemplate: `Analyze diversity metrics:\n\n{{input}}\n\nReport: Demographics, pipeline, retention, promotion rates, client requirements, improvement strategies.`,
    systemPrompt: 'You are a diversity and inclusion consultant.',
    maxTokens: 4000,
    temperature: 0.5,
    wave: 4,
  },
  {
    name: 'Pro Bono Matter Matcher',
    slug: 'pro-bono-matter-matcher',
    description: 'Match attorneys with pro bono opportunities',
    category: 'client-management',
    inputType: 'structured',
    outputType: 'json',
    pricingTier: 'free',
    promptTemplate: `Match pro bono opportunity:\n\n{{input}}\n\nConsider: Practice area, time commitment, skill development, client needs, supervision available.`,
    systemPrompt: 'You are a pro bono coordinator.',
    maxTokens: 2000,
    temperature: 0.5,
    wave: 4,
  },
]
